# Run a classifer on the branchwater search output

In [33]:
# base checkout of workflow directory is here:
BASE='/home/ctbrown/scratch3/2025-workflow-core99/'

# parquet files from branchwater
#BASE_OUTPUTS=BASE+'/outputs.branchwater'

MIN=90
SCALED=1000
HASH_THRESHOLD=int(30000 / SCALED)

#BASE_OUTPUTS=BASE+f'/outputs.mapping/cds/singlehash.k21/outputs.branchwater.min{MIN}.scaled{SCALED}'
BASE_OUTPUTS=BASE+'/outputs.mapping/cds2/outputs.branchwater'

In [34]:
import polars as pl
import numpy as np
import sklearn.tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold

In [35]:
dirpath = BASE_OUTPUTS+'/*.parquet'

bw_df = pl.scan_parquet(dirpath).collect()
bw_df = bw_df.with_columns(pl.col("query_name").alias("species"),
                           pl.col("match_name").alias("acc"))
bw_df = bw_df.select(["species", "acc", "containment", "intersect_hashes"])

# mimic the Web site search threshold of 0.1
bw_df = bw_df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)
bw_df

shape: (837_216, 4)
┌─────────────────────────────────┬─────────────┬─────────────┬──────────────────┐
│ species                         ┆ acc         ┆ containment ┆ intersect_hashes │
│ ---                             ┆ ---         ┆ ---         ┆ ---              │
│ str                             ┆ str         ┆ f64         ┆ i64              │
╞═════════════════════════════════╪═════════════╪═════════════╪══════════════════╡
│ s__Cryptobacteroides sp9005469… ┆ ERR2241781  ┆ 0.943182    ┆ 83               │
│ s__Cryptobacteroides sp9005469… ┆ ERR2245331  ┆ 0.931818    ┆ 82               │
│ s__Cryptobacteroides sp9005469… ┆ ERR2241717  ┆ 0.931818    ┆ 82               │
│ s__Cryptobacteroides sp9005469… ┆ ERR2241627  ┆ 0.931818    ┆ 82               │
│ s__Cryptobacteroides sp9005469… ┆ SRR17241507 ┆ 0.931818    ┆ 82               │
│ …                               ┆ …           ┆ …           ┆ …                │
│ s__Sodaliphilus sp004557565     ┆ SRR3977439  ┆ 0.017953    ┆ 30               │
│ s__Sodaliphilus sp004557565     ┆ ERR4334063  ┆ 0.017953    ┆ 30               │
│ s__Sodaliphilus sp004557565     ┆ SRR21738316 ┆ 0.017953    ┆ 30               │
│ s__Sodaliphilus sp004557565     ┆ SRR21518425 ┆ 0.017953    ┆ 30               │
│ s__Sodaliphilus sp004557565     ┆ SRR8638153  ┆ 0.017953    ┆ 30               │
└─────────────────────────────────┴─────────────┴─────────────┴──────────────────┘

In [36]:
metadata_df = pl.scan_parquet('/group/ctbrowngrp5/sra-metagenomes/20241128-metadata.parquet')
metadata_df = metadata_df.select(["acc", "organism", "assay_type"])\
    .filter(pl.col("acc") != "NP")\
    .filter(pl.col("assay_type") == "WGS")

metadata_df = metadata_df.collect()
metadata_df

shape: (703_916, 3)
┌─────────────┬───────────────────────┬────────────┐
│ acc         ┆ organism              ┆ assay_type │
│ ---         ┆ ---                   ┆ ---        │
│ str         ┆ str                   ┆ str        │
╞═════════════╪═══════════════════════╪════════════╡
│ SRR28523869 ┆ human metagenome      ┆ WGS        │
│ SRR19901137 ┆ Streptococcus suis    ┆ WGS        │
│ SRR24962475 ┆ Escherichia coli      ┆ WGS        │
│ SRR29161330 ┆ biofilm metagenome    ┆ WGS        │
│ SRR26668739 ┆ bovine gut metagenome ┆ WGS        │
│ …           ┆ …                     ┆ …          │
│ ERR4174288  ┆ human gut metagenome  ┆ WGS        │
│ ERR3160109  ┆ human gut metagenome  ┆ WGS        │
│ ERR2709457  ┆ human gut metagenome  ┆ WGS        │
│ ERR2709367  ┆ human gut metagenome  ┆ WGS        │
│ ERR2709388  ┆ human gut metagenome  ┆ WGS        │
└─────────────┴───────────────────────┴────────────┘

In [37]:
bw_df = bw_df.join(metadata_df, on="acc", how="left")
bw_df

shape: (837_216, 6)
┌───────────────────┬─────────────┬─────────────┬──────────────────┬──────────────────┬────────────┐
│ species           ┆ acc         ┆ containment ┆ intersect_hashes ┆ organism         ┆ assay_type │
│ ---               ┆ ---         ┆ ---         ┆ ---              ┆ ---              ┆ ---        │
│ str               ┆ str         ┆ f64         ┆ i64              ┆ str              ┆ str        │
╞═══════════════════╪═════════════╪═════════════╪══════════════════╪══════════════════╪════════════╡
│ s__Cryptobacteroi ┆ ERR2241781  ┆ 0.943182    ┆ 83               ┆ metagenome       ┆ WGS        │
│ des sp9005469…    ┆             ┆             ┆                  ┆                  ┆            │
│ s__Cryptobacteroi ┆ ERR2245331  ┆ 0.931818    ┆ 82               ┆ metagenome       ┆ WGS        │
│ des sp9005469…    ┆             ┆             ┆                  ┆                  ┆            │
│ s__Cryptobacteroi ┆ ERR2241717  ┆ 0.931818    ┆ 82               ┆ metagenome       ┆ WGS        │
│ des sp9005469…    ┆             ┆             ┆                  ┆                  ┆            │
│ s__Cryptobacteroi ┆ ERR2241627  ┆ 0.931818    ┆ 82               ┆ metagenome       ┆ WGS        │
│ des sp9005469…    ┆             ┆             ┆                  ┆                  ┆            │
│ s__Cryptobacteroi ┆ SRR17241507 ┆ 0.931818    ┆ 82               ┆ pig gut          ┆ WGS        │
│ des sp9005469…    ┆             ┆             ┆                  ┆ metagenome       ┆            │
│ …                 ┆ …           ┆ …           ┆ …                ┆ …                ┆ …          │
│ s__Sodaliphilus   ┆ SRR3977439  ┆ 0.017953    ┆ 30               ┆ soil metagenome  ┆ WGS        │
│ sp004557565       ┆             ┆             ┆                  ┆                  ┆            │
│ s__Sodaliphilus   ┆ ERR4334063  ┆ 0.017953    ┆ 30               ┆ gut metagenome   ┆ WGS        │
│ sp004557565       ┆             ┆             ┆                  ┆                  ┆            │
│ s__Sodaliphilus   ┆ SRR21738316 ┆ 0.017953    ┆ 30               ┆ mouse gut        ┆ WGS        │
│ sp004557565       ┆             ┆             ┆                  ┆ metagenome       ┆            │
│ s__Sodaliphilus   ┆ SRR21518425 ┆ 0.017953    ┆ 30               ┆ human oral       ┆ WGS        │
│ sp004557565       ┆             ┆             ┆                  ┆ metagenome       ┆            │
│ s__Sodaliphilus   ┆ SRR8638153  ┆ 0.017953    ┆ 30               ┆ gut metagenome   ┆ WGS        │
│ sp004557565       ┆             ┆             ┆                  ┆                  ┆            │
└───────────────────┴─────────────┴─────────────┴──────────────────┴──────────────────┴────────────┘

In [38]:
bw_df['organism'].value_counts().sort(by='count', descending=True)

shape: (551, 2)
┌─────────────────────────────┬────────┐
│ organism                    ┆ count  │
│ ---                         ┆ ---    │
│ str                         ┆ u32    │
╞═════════════════════════════╪════════╡
│ human gut metagenome        ┆ 337286 │
│ gut metagenome              ┆ 82541  │
│ null                        ┆ 81679  │
│ metagenome                  ┆ 65298  │
│ pig gut metagenome          ┆ 49435  │
│ …                           ┆ …      │
│ Sphingomonas                ┆ 1      │
│ Streptococcus parasanguinis ┆ 1      │
│ Klebsiella oxytoca          ┆ 1      │
│ Nomascus siki               ┆ 1      │
│ Meles meles                 ┆ 1      │
└─────────────────────────────┴────────┘

In [39]:
rename_df = []
for organism in bw_df['organism'].unique().to_list():
    simpleorg = 'unknown'
    if organism:
        organism = organism.lower()
        for kw in ['human', 'homo']:
            if kw in organism.lower():
                simpleorg = 'human'
                break
        for kw in ['pig', 'sus', 'scrofa']:
            if kw in organism.lower():
                simpleorg = 'pig'
                break
    rename_df.append(dict(organism=organism, simpleorg=simpleorg))

rename_df = pl.DataFrame(rename_df)
rename_df['simpleorg'].value_counts().sort(by='count', descending=True)

shape: (3, 2)
┌───────────┬───────┐
│ simpleorg ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ unknown   ┆ 524   │
│ human     ┆ 18    │
│ pig       ┆ 9     │
└───────────┴───────┘

In [40]:
rename_df

shape: (551, 2)
┌─────────────────────────────────┬───────────┐
│ organism                        ┆ simpleorg │
│ ---                             ┆ ---       │
│ str                             ┆ str       │
╞═════════════════════════════════╪═══════════╡
│ equus asinus                    ┆ unknown   │
│ marsupial metagenome            ┆ unknown   │
│ romboutsia timonensis           ┆ unknown   │
│ subdoligranulum sp. ds11        ┆ unknown   │
│ nomascus gabriellae             ┆ unknown   │
│ …                               ┆ …         │
│ pinnotheres pholadis            ┆ unknown   │
│ candidatus minimicrobia sp. ih… ┆ unknown   │
│ rabbit gut metagenome           ┆ unknown   │
│ cave metagenome                 ┆ unknown   │
│ choloepus hoffmanni             ┆ unknown   │
└─────────────────────────────────┴───────────┘

In [41]:
# add a new column with a simplified organism
bw_df = bw_df.join(rename_df, on='organism', how='inner', coalesce=True).select(['acc', 'organism', 'species', 'simpleorg'])
bw_df.select(['acc', 'simpleorg']).unique()['simpleorg'].value_counts()

shape: (3, 2)
┌───────────┬────────┐
│ simpleorg ┆ count  │
│ ---       ┆ ---    │
│ str       ┆ u32    │
╞═══════════╪════════╡
│ unknown   ┆ 110177 │
│ human     ┆ 147998 │
│ pig       ┆ 6748   │
└───────────┴────────┘

In [42]:
bw_df

shape: (712_386, 4)
┌─────────────┬───────────────────────┬─────────────────────────────────┬───────────┐
│ acc         ┆ organism              ┆ species                         ┆ simpleorg │
│ ---         ┆ ---                   ┆ ---                             ┆ ---       │
│ str         ┆ str                   ┆ str                             ┆ str       │
╞═════════════╪═══════════════════════╪═════════════════════════════════╪═══════════╡
│ ERR2241781  ┆ metagenome            ┆ s__Cryptobacteroides sp9005469… ┆ unknown   │
│ ERR2245331  ┆ metagenome            ┆ s__Cryptobacteroides sp9005469… ┆ unknown   │
│ ERR2241717  ┆ metagenome            ┆ s__Cryptobacteroides sp9005469… ┆ unknown   │
│ ERR2241627  ┆ metagenome            ┆ s__Cryptobacteroides sp9005469… ┆ unknown   │
│ SRR17241507 ┆ pig gut metagenome    ┆ s__Cryptobacteroides sp9005469… ┆ pig       │
│ …           ┆ …                     ┆ …                               ┆ …         │
│ SRR3977439  ┆ soil metagenome       ┆ s__Sodaliphilus sp004557565     ┆ unknown   │
│ ERR4334063  ┆ gut metagenome        ┆ s__Sodaliphilus sp004557565     ┆ unknown   │
│ SRR21738316 ┆ mouse gut metagenome  ┆ s__Sodaliphilus sp004557565     ┆ unknown   │
│ SRR21518425 ┆ human oral metagenome ┆ s__Sodaliphilus sp004557565     ┆ human     │
│ SRR8638153  ┆ gut metagenome        ┆ s__Sodaliphilus sp004557565     ┆ unknown   │
└─────────────┴───────────────────────┴─────────────────────────────────┴───────────┘

In [43]:
def make_matrices(df):
    acc_df = df['acc'].unique().to_frame().with_row_index(name='acc_index')
    species_df = df['species'].unique().to_frame().with_row_index(name='species_index')
    org_df = df['simpleorg'].unique().to_frame().with_row_index(name='org_index')

    df = df.join(org_df, on='simpleorg', how='left')
    df = df.join(acc_df, on='acc', how='left')
    df = df.join(species_df, on='species', how='left')

    obs = np.zeros((len(acc_df), len(species_df)))
    target = np.zeros((len(acc_df)))

    for row in df.iter_rows(named=True):
        acc_id = row["acc_index"]
        org_id = row["org_index"]
        species_id = row["species_index"]

        obs[acc_id, species_id] = 1
        target[acc_id] = org_id

    print(f'observations matrix shape is: {obs.shape}')

    return df, obs, target

In [44]:
human_pig_only = bw_df.filter(pl.col("simpleorg") != "unknown")
hp_df, hp_obs, hp_target = make_matrices(human_pig_only)

observations matrix shape is: (154746, 10)

In [45]:
hp_df

shape: (428_785, 7)
┌─────────────┬────────────┬───────────────────┬───────────┬───────────┬───────────┬───────────────┐
│ acc         ┆ organism   ┆ species           ┆ simpleorg ┆ org_index ┆ acc_index ┆ species_index │
│ ---         ┆ ---        ┆ ---               ┆ ---       ┆ ---       ┆ ---       ┆ ---           │
│ str         ┆ str        ┆ str               ┆ str       ┆ u32       ┆ u32       ┆ u32           │
╞═════════════╪════════════╪═══════════════════╪═══════════╪═══════════╪═══════════╪═══════════════╡
│ SRR17241507 ┆ pig gut    ┆ s__Cryptobacteroi ┆ pig       ┆ 1         ┆ 59361     ┆ 7             │
│             ┆ metagenome ┆ des sp9005469…    ┆           ┆           ┆           ┆               │
│ SRR17241627 ┆ pig gut    ┆ s__Cryptobacteroi ┆ pig       ┆ 1         ┆ 130717    ┆ 7             │
│             ┆ metagenome ┆ des sp9005469…    ┆           ┆           ┆           ┆               │
│ SRR17241612 ┆ pig gut    ┆ s__Cryptobacteroi ┆ pig       ┆ 1         ┆ 33643     ┆ 7             │
│             ┆ metagenome ┆ des sp9005469…    ┆           ┆           ┆           ┆               │
│ SRR17241482 ┆ pig gut    ┆ s__Cryptobacteroi ┆ pig       ┆ 1         ┆ 20766     ┆ 7             │
│             ┆ metagenome ┆ des sp9005469…    ┆           ┆           ┆           ┆               │
│ SRR27108392 ┆ pig gut    ┆ s__Cryptobacteroi ┆ pig       ┆ 1         ┆ 77820     ┆ 7             │
│             ┆ metagenome ┆ des sp9005469…    ┆           ┆           ┆           ┆               │
│ …           ┆ …          ┆ …                 ┆ …         ┆ …         ┆ …         ┆ …             │
│ ERR7500090  ┆ human gut  ┆ s__Sodaliphilus   ┆ human     ┆ 0         ┆ 41904     ┆ 1             │
│             ┆ metagenome ┆ sp004557565       ┆           ┆           ┆           ┆               │
│ SRR15032276 ┆ human gut  ┆ s__Sodaliphilus   ┆ human     ┆ 0         ┆ 59266     ┆ 1             │
│             ┆ metagenome ┆ sp004557565       ┆           ┆           ┆           ┆               │
│ ERR11474294 ┆ human gut  ┆ s__Sodaliphilus   ┆ human     ┆ 0         ┆ 132970    ┆ 1             │
│             ┆ metagenome ┆ sp004557565       ┆           ┆           ┆           ┆               │
│ ERR11472732 ┆ human gut  ┆ s__Sodaliphilus   ┆ human     ┆ 0         ┆ 75396     ┆ 1             │
│             ┆ metagenome ┆ sp004557565       ┆           ┆           ┆           ┆               │
│ SRR21518425 ┆ human oral ┆ s__Sodaliphilus   ┆ human     ┆ 0         ┆ 707       ┆ 1             │
│             ┆ metagenome ┆ sp004557565       ┆           ┆           ┆           ┆               │
└─────────────┴────────────┴───────────────────┴───────────┴───────────┴───────────┴───────────────┘

## 6-Fold Cross Validation approach

Run 6 different splits of the data; train on 1/6 of the data and test on the other 5/6s of the data, and then repeat that for each of the 6 splits.

In [46]:
kf = StratifiedKFold(n_splits=6)

accuracies = []
i = 1
for train_sub, test_sub in kf.split(hp_obs, hp_target):
    dt = DecisionTreeClassifier(random_state=42)
    tree = dt.fit(hp_obs[train_sub], hp_target[train_sub])
    pred = tree.predict(hp_obs[test_sub])

    accuracy = balanced_accuracy_score(hp_target[test_sub], pred)
    accuracies.append(accuracy)
    print(f"iteration {i}: accuracy {accuracy:.3f}")
    i += 1

print(f"mean accuracy across {i-1} splits: {np.mean(accuracies):.3f}")

iteration 1: accuracy 0.931
iteration 2: accuracy 0.929
iteration 3: accuracy 0.942
iteration 4: accuracy 0.942
iteration 5: accuracy 0.942
iteration 6: accuracy 0.938
mean accuracy across 6 splits: 0.937

## What do we after 6-fold cross validation?

This approach lets us check to see that, in general, the performance of any classifer trained on this data will be pretty good - independent of which set of data we use.

Now, to train the best possible classifier for _future_ use, we will use all the data to train:

In [47]:
dt = DecisionTreeClassifier(random_state=42)
tree = dt.fit(hp_obs, hp_target)
pred = tree.predict(hp_obs)

accuracy = balanced_accuracy_score(hp_target, pred)
print(f"full classifier: accuracy {accuracy:.3f}")

full classifier: accuracy 0.940

## What do we do with the full classifier now??

Now we can go back to the original data - not just the human/pig subset, but the one with unknowns. (Or, potentially, new data sets.)

The only thing we need to be careful about is to encode new observations using the species indexes that match the trained classifier, as well as the organism indexes (0 pig, 1 human). Let's extract those:

In [48]:
species_index_df = hp_df.select(['species_index', 'species']).unique()
species_index_df

shape: (10, 2)
┌───────────────┬─────────────────────────────────┐
│ species_index ┆ species                         │
│ ---           ┆ ---                             │
│ u32           ┆ str                             │
╞═══════════════╪═════════════════════════════════╡
│ 0             ┆ s__Gemmiger qucibialis          │
│ 2             ┆ s__Roseburia inulinivorans      │
│ 4             ┆ s__Prevotella sp002251295       │
│ 3             ┆ s__Mogibacterium_A kristiansen… │
│ 5             ┆ s__Prevotella sp000434975       │
│ 1             ┆ s__Sodaliphilus sp004557565     │
│ 6             ┆ s__Lactobacillus amylovorus     │
│ 7             ┆ s__Cryptobacteroides sp9005469… │
│ 9             ┆ s__JALFVM01 sp022787145         │
│ 8             ┆ s__Phascolarctobacterium_A suc… │
└───────────────┴─────────────────────────────────┘

In [49]:
org_df = hp_df.select(['org_index', 'simpleorg']).unique()
org_df

shape: (2, 2)
┌───────────┬───────────┐
│ org_index ┆ simpleorg │
│ ---       ┆ ---       │
│ u32       ┆ str       │
╞═══════════╪═══════════╡
│ 0         ┆ human     │
│ 1         ┆ pig       │
└───────────┴───────────┘

Now, let's take some of some of the data we didn't touch from the original bw_df, and encode and classify it:

In [50]:
def make_obs_matrix(df, species_df):
    # need a new access mapping
    acc_df = df['acc'].unique().to_frame().with_row_index(name='acc_index')

    # construct new internal data frame, populate
    df = df.join(acc_df, on='acc', how='left')
    df = df.join(species_df, on='species', how='left')

    obs = np.zeros((len(acc_df), len(species_df)))

    for row in df.iter_rows(named=True):
        acc_id = row["acc_index"]
        species_id = row["species_index"]

        obs[acc_id, species_id] = 1

    print(f'observations matrix shape is: {obs.shape}')

    return df, obs

In [51]:
unknown_only_df = bw_df.filter(pl.col("simpleorg") == "unknown")
unk_df, unk_obs = make_obs_matrix(unknown_only_df, species_index_df)

observations matrix shape is: (110177, 10)

In [52]:
unknown_pred = tree.predict(unk_obs)
unknown_pred

array([0., 0., 0., ..., 0., 0., 0.], shape=(110177,))

## Predictions are great and all but...

Great! XXX predictions 😭 . What do we do with them??

Let's merge the predictions back into the spreadsheet.

In [53]:
unk_pred_df = []
for (row_n, predicted_org) in enumerate(unknown_pred):
    unk_pred_df.append(dict(acc_index=row_n, org_index=int(predicted_org)))
unk_pred_df = pl.DataFrame(unk_pred_df).join(org_df, on='org_index', how='left')

unk_acc_df = unk_df.select(["acc", "acc_index"]).unique()

unk_pred_df = unk_pred_df.join(unk_acc_df, on='acc_index', how='left')
unk_pred_df

shape: (110_177, 4)
┌───────────┬───────────┬───────────┬─────────────┐
│ acc_index ┆ org_index ┆ simpleorg ┆ acc         │
│ ---       ┆ ---       ┆ ---       ┆ ---         │
│ i64       ┆ i64       ┆ str       ┆ str         │
╞═══════════╪═══════════╪═══════════╪═════════════╡
│ 0         ┆ 0         ┆ human     ┆ SRR25919804 │
│ 1         ┆ 0         ┆ human     ┆ ERR2607379  │
│ 2         ┆ 0         ┆ human     ┆ SRR9006654  │
│ 3         ┆ 0         ┆ human     ┆ SRR23829180 │
│ 4         ┆ 0         ┆ human     ┆ SRR8436477  │
│ …         ┆ …         ┆ …         ┆ …           │
│ 110172    ┆ 0         ┆ human     ┆ SRR28085345 │
│ 110173    ┆ 0         ┆ human     ┆ SRR29291360 │
│ 110174    ┆ 0         ┆ human     ┆ SRR14576915 │
│ 110175    ┆ 0         ┆ human     ┆ ERR11560444 │
│ 110176    ┆ 0         ┆ human     ┆ SRR23018262 │
└───────────┴───────────┴───────────┴─────────────┘

In [54]:
unk_pred_df["simpleorg"].value_counts().sort(by='count', descending=True)

shape: (2, 2)
┌───────────┬────────┐
│ simpleorg ┆ count  │
│ ---       ┆ ---    │
│ str       ┆ u32    │
╞═══════════╪════════╡
│ human     ┆ 105957 │
│ pig       ┆ 4220   │
└───────────┴────────┘

## OK! We have our predictions... did this actually work?

In [55]:
# sample 5 randomly
unk_pred_df.sample(n=5)

shape: (5, 4)
┌───────────┬───────────┬───────────┬─────────────┐
│ acc_index ┆ org_index ┆ simpleorg ┆ acc         │
│ ---       ┆ ---       ┆ ---       ┆ ---         │
│ i64       ┆ i64       ┆ str       ┆ str         │
╞═══════════╪═══════════╪═══════════╪═════════════╡
│ 84650     ┆ 0         ┆ human     ┆ SRR28426745 │
│ 15587     ┆ 0         ┆ human     ┆ ERR10789547 │
│ 107458    ┆ 1         ┆ pig       ┆ SRR25429141 │
│ 53189     ┆ 0         ┆ human     ┆ SRR14509794 │
│ 37593     ┆ 0         ┆ human     ┆ SRR28005884 │
└───────────┴───────────┴───────────┴─────────────┘

In [56]:
# sample 5 predicted as pig
unk_pred_df.filter(pl.col("simpleorg") == "pig").sample(n=5)

shape: (5, 4)
┌───────────┬───────────┬───────────┬─────────────┐
│ acc_index ┆ org_index ┆ simpleorg ┆ acc         │
│ ---       ┆ ---       ┆ ---       ┆ ---         │
│ i64       ┆ i64       ┆ str       ┆ str         │
╞═══════════╪═══════════╪═══════════╪═════════════╡
│ 36393     ┆ 1         ┆ pig       ┆ ERR3574772  │
│ 25352     ┆ 1         ┆ pig       ┆ SRR13618049 │
│ 65461     ┆ 1         ┆ pig       ┆ ERR3574458  │
│ 93715     ┆ 1         ┆ pig       ┆ ERR2597344  │
│ 38600     ┆ 1         ┆ pig       ┆ SRR29188462 │
└───────────┴───────────┴───────────┴─────────────┘

In [57]:
# sample 5 predicted as human
unk_pred_df.filter(pl.col("simpleorg") == "human").sample(n=5)

shape: (5, 4)
┌───────────┬───────────┬───────────┬─────────────┐
│ acc_index ┆ org_index ┆ simpleorg ┆ acc         │
│ ---       ┆ ---       ┆ ---       ┆ ---         │
│ i64       ┆ i64       ┆ str       ┆ str         │
╞═══════════╪═══════════╪═══════════╪═════════════╡
│ 34115     ┆ 0         ┆ human     ┆ ERR4335067  │
│ 94994     ┆ 0         ┆ human     ┆ SRR14373445 │
│ 107144    ┆ 0         ┆ human     ┆ SRR29188468 │
│ 7322      ┆ 0         ┆ human     ┆ SRR11172600 │
│ 33305     ┆ 0         ┆ human     ┆ SRR28426948 │
└───────────┴───────────┴───────────┴─────────────┘

# What features are most important for good classification?

First, let's get the feature importances.

In [58]:
importances_df = []
for (species_index, importance) in enumerate(tree.feature_importances_):
    d = dict(species_index=species_index, importance=importance)
    importances_df.append(d)

importances_df = pl.DataFrame(importances_df)
importances_df = importances_df.join(species_index_df, on='species_index', how='left')
importances_df = importances_df.sort(by='importance', descending=True)
importances_df

shape: (10, 3)
┌───────────────┬────────────┬─────────────────────────────────┐
│ species_index ┆ importance ┆ species                         │
│ ---           ┆ ---        ┆ ---                             │
│ i64           ┆ f64        ┆ str                             │
╞═══════════════╪════════════╪═════════════════════════════════╡
│ 6             ┆ 0.839003   ┆ s__Lactobacillus amylovorus     │
│ 4             ┆ 0.071608   ┆ s__Prevotella sp002251295       │
│ 2             ┆ 0.048103   ┆ s__Roseburia inulinivorans      │
│ 9             ┆ 0.017197   ┆ s__JALFVM01 sp022787145         │
│ 3             ┆ 0.007647   ┆ s__Mogibacterium_A kristiansen… │
│ 5             ┆ 0.004916   ┆ s__Prevotella sp000434975       │
│ 1             ┆ 0.004785   ┆ s__Sodaliphilus sp004557565     │
│ 7             ┆ 0.004782   ┆ s__Cryptobacteroides sp9005469… │
│ 0             ┆ 0.001294   ┆ s__Gemmiger qucibialis          │
│ 8             ┆ 0.000666   ┆ s__Phascolarctobacterium_A suc… │
└───────────────┴────────────┴─────────────────────────────────┘

Now let's rebuild the classifier after removing each species, and see how well it does...

In [59]:
species_in_order = importances_df['species'].to_list()
species_in_order

['s__Lactobacillus amylovorus',
 's__Prevotella sp002251295',
 's__Roseburia inulinivorans',
 's__JALFVM01 sp022787145',
 's__Mogibacterium_A kristiansenii',
 's__Prevotella sp000434975',
 's__Sodaliphilus sp004557565',
 's__Cryptobacteroides sp900546925',
 's__Gemmiger qucibialis',
 's__Phascolarctobacterium_A succinatutens']

In [60]:
human_pig_only = bw_df.filter(pl.col("simpleorg") != "unknown")
species_to_rm = list(species_in_order)

remove_df = human_pig_only
while len(species_to_rm) >= 2:
    rm_species = species_to_rm.pop(0)
    print(f'removing {rm_species} too')
    if len(species_to_rm) == 1:
        print('left:', species_to_rm[0])

    remove_df = remove_df.filter(pl.col("species") != rm_species)
    augmented_df, rm_obs, rm_target = make_matrices(remove_df)

    dt = DecisionTreeClassifier(random_state=42)
    tree = dt.fit(rm_obs, rm_target)
    pred = tree.predict(rm_obs)

    accuracy = balanced_accuracy_score(rm_target, pred)
    print(f"classifier accuracy with {remove_df['species'].n_unique()} is: {accuracy:.3f}")
    print('---')

removing s__Lactobacillus amylovorus too
observations matrix shape is: (154746, 9)
classifier accuracy with 9 is: 0.934
---
removing s__Prevotella sp002251295 too
observations matrix shape is: (154746, 8)
classifier accuracy with 8 is: 0.918
---
removing s__Roseburia inulinivorans too
observations matrix shape is: (154604, 7)
classifier accuracy with 7 is: 0.879
---
removing s__JALFVM01 sp022787145 too
observations matrix shape is: (154604, 6)
classifier accuracy with 6 is: 0.895
---
removing s__Mogibacterium_A kristiansenii too
observations matrix shape is: (154591, 5)
classifier accuracy with 5 is: 0.893
---
removing s__Prevotella sp000434975 too
observations matrix shape is: (153762, 4)
classifier accuracy with 4 is: 0.894
---
removing s__Sodaliphilus sp004557565 too
observations matrix shape is: (152124, 3)
classifier accuracy with 3 is: 0.908
---
removing s__Cryptobacteroides sp900546925 too
observations matrix shape is: (152124, 2)
classifier accuracy with 2 is: 0.500
---
removing s__Gemmiger qucibialis too
left: s__Phascolarctobacterium_A succinatutens
observations matrix shape is: (25924, 1)
classifier accuracy with 1 is: 0.500
---

## Remove in reverse order...

In [61]:
human_pig_only = bw_df.filter(pl.col("simpleorg") != "unknown")
species_to_rm = list(reversed(species_in_order))

remove_df = human_pig_only
while len(species_to_rm) >= 2:
    rm_species = species_to_rm.pop(0)
    print(f'removing {rm_species} too')

    remove_df = remove_df.filter(pl.col("species") != rm_species)
    augmented_df, rm_obs, rm_target = make_matrices(remove_df)

    dt = DecisionTreeClassifier(random_state=42)
    tree = dt.fit(rm_obs, rm_target)
    pred = tree.predict(rm_obs)

    accuracy = balanced_accuracy_score(rm_target, pred)
    print(f"classifier accuracy with {remove_df['species'].n_unique()} is: {accuracy:.3f}")
    print('---')

removing s__Phascolarctobacterium_A succinatutens too
observations matrix shape is: (154495, 9)
classifier accuracy with 9 is: 0.941
---
removing s__Gemmiger qucibialis too
observations matrix shape is: (104941, 8)
classifier accuracy with 8 is: 0.940
---
removing s__Cryptobacteroides sp900546925 too
observations matrix shape is: (104941, 7)
classifier accuracy with 7 is: 0.946
---
removing s__Sodaliphilus sp004557565 too
observations matrix shape is: (103504, 6)
classifier accuracy with 6 is: 0.951
---
removing s__Prevotella sp000434975 too
observations matrix shape is: (91070, 5)
classifier accuracy with 5 is: 0.957
---
removing s__Mogibacterium_A kristiansenii too
observations matrix shape is: (81538, 4)
classifier accuracy with 4 is: 0.999
---
removing s__JALFVM01 sp022787145 too
observations matrix shape is: (81359, 3)
classifier accuracy with 3 is: 0.995
---
removing s__Roseburia inulinivorans too
observations matrix shape is: (5845, 2)
classifier accuracy with 2 is: 0.500
---
removing s__Prevotella sp002251295 too
observations matrix shape is: (5316, 1)
classifier accuracy with 1 is: 0.500
---

In [62]:
human_pig_only['species'].unique().to_list()

['s__Prevotella sp002251295',
 's__Gemmiger qucibialis',
 's__Phascolarctobacterium_A succinatutens',
 's__JALFVM01 sp022787145',
 's__Roseburia inulinivorans',
 's__Prevotella sp000434975',
 's__Mogibacterium_A kristiansenii',
 's__Cryptobacteroides sp900546925',
 's__Lactobacillus amylovorus',
 's__Sodaliphilus sp004557565']

In [63]:
SUB_SPECIES=('s__Cryptobacteroides sp900546925',
             's__Phascolarctobacterium_A succinatutens',
             's__Mogibacterium_A kristiansenii',
             's__Prevotella sp002251295',
             's__Prevotella sp000434975',
             's__Holdemanella porci',
             's__Bariatricus sp004560705',
             's__Fimisoma sp002320005',
             's__Gemmiger qucibialis',
             's__JAFBIX01 sp021531895',
             's__JALFVM01 sp022787145',
             's__Lactobacillus amylovorus',
             's__Roseburia inulinivorans',
             's__Sodaliphilus sp004557565',
             's__UBA2868 sp004552595',
)
SUB_SPECIES2=(
             's__Cryptobacteroides sp900546925',
             's__Phascolarctobacterium_A succinatutens',
             's__Mogibacterium_A kristiansenii',
             's__Prevotella sp002251295',
#             's__Prevotella sp000434975',
#             's__Holdemanella porci',
)
human_pig_only = bw_df.filter(pl.col("simpleorg") != "unknown")
remove_df = human_pig_only.filter(pl.col("species").is_in(set(SUB_SPECIES2)))
assert len(remove_df)

augmented_df, rm_obs, rm_target = make_matrices(remove_df)

dt = DecisionTreeClassifier(random_state=42)
tree = dt.fit(rm_obs, rm_target)
pred = tree.predict(rm_obs)

accuracy = balanced_accuracy_score(rm_target, pred)
print(f"classifier accuracy with {remove_df['species'].n_unique()} is: {accuracy:.3f}")

observations matrix shape is: (69365, 4)
classifier accuracy with 4 is: 0.931