# Look at mapping breadth and depth of 100+ metagenomes to singleclust genes - highcov version

In [1]:
import polars as pl
import glob
import os
import screed
import csv
import screed

## Read in individual metag x species singleclust depth reports

These files contain depth-of-mapping information for all our genes.

In [3]:
DIR='../outputs.cds/singleclust.highcov/bam'
template = '../outputs.cds/singleclust.highcov/bam/{metag}.x.{species}.depth.txt'

def read_depth_txt(metag, species, *, exclude_ends=75):
    filename = template.format(metag=metag, species=species)
    df = pl.read_csv(filename, separator='\t', has_header=False,
                 new_columns=('gene', 'pos', 'cov', 'foo')).select(['gene', 'pos', 'cov'])

    sum_df = df.group_by('gene').all().with_columns(
        # select slice [75:-75]
        (pl.col("pos").list.slice(exclude_ends, -exclude_ends).list.len()).alias("len"),
        (pl.col("cov").list.slice(exclude_ends, -exclude_ends)),
        (pl.col("cov").list.slice(exclude_ends, -exclude_ends).list.filter(pl.element() > 0)).list.len().alias("hits"),
    ).with_columns(
        (pl.lit(metag).alias("metag")),
        (pl.lit(species).alias("species")),
        # summarize: average depth across contig,
        (pl.col("cov").list.sum() / pl.col("len")).alias("depth_all"),
        # average depth across covered bases,
        (pl.col("cov").list.sum() / pl.col("hits")).alias("depth_cov"),
        # fraction of bases covered
        (pl.col("hits") / pl.col("cov").list.len()).alias("breadth"),
    ).select(["metag", "species", "gene", "len", "hits", "breadth", "depth_all", "depth_cov"])
    return sum_df

read_depth_txt('SRR8960963', 's__Cryptobacteroides sp900546925')

shape: (248, 8)
┌────────────┬───────────────────┬────────────────┬──────┬──────┬──────────┬───────────┬───────────┐
│ metag      ┆ species           ┆ gene           ┆ len  ┆ hits ┆ breadth  ┆ depth_all ┆ depth_cov │
│ ---        ┆ ---               ┆ ---            ┆ ---  ┆ ---  ┆ ---      ┆ ---       ┆ ---       │
│ str        ┆ str               ┆ str            ┆ u32  ┆ u32  ┆ f64      ┆ f64       ┆ f64       │
╞════════════╪═══════════════════╪════════════════╪══════╪══════╪══════════╪═══════════╪═══════════╡
│ SRR8960963 ┆ s__Cryptobacteroi ┆ NMJBBHDE_00454 ┆ 771  ┆ 771  ┆ 1.0      ┆ 25.175097 ┆ 25.175097 │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ SRR8960963 ┆ s__Cryptobacteroi ┆ LELOEEPG_00175 ┆ 1047 ┆ 879  ┆ 0.839542 ┆ 12.006686 ┆ 14.301479 │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ SRR8960963 ┆ s__Cryptobacteroi ┆ MFHJPMDA_01033 ┆ 1137 ┆ 998  ┆ 0.877748 ┆ 2.664908  ┆ 3.036072  │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ SRR8960963 ┆ s__Cryptobacteroi ┆ FNIGJHLI_02574 ┆ 1101 ┆ 0    ┆ 0.0      ┆ 0.0       ┆ NaN       │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ SRR8960963 ┆ s__Cryptobacteroi ┆ FNIGJHLI_00373 ┆ 1644 ┆ 1639 ┆ 0.996959 ┆ 25.844891 ┆ 25.923734 │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ …          ┆ …                 ┆ …              ┆ …    ┆ …    ┆ …        ┆ …         ┆ …         │
│ SRR8960963 ┆ s__Cryptobacteroi ┆ EHLNOCPD_01770 ┆ 765  ┆ 499  ┆ 0.652288 ┆ 13.566013 ┆ 20.797595 │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ SRR8960963 ┆ s__Cryptobacteroi ┆ NLDKNCOF_00688 ┆ 1308 ┆ 1304 ┆ 0.996942 ┆ 17.939602 ┆ 17.994632 │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ SRR8960963 ┆ s__Cryptobacteroi ┆ HLFEEHJE_00119 ┆ 177  ┆ 177  ┆ 1.0      ┆ 15.350282 ┆ 15.350282 │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ SRR8960963 ┆ s__Cryptobacteroi ┆ ILFIENBF_01329 ┆ 879  ┆ 879  ┆ 1.0      ┆ 30.263936 ┆ 30.263936 │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ SRR8960963 ┆ s__Cryptobacteroi ┆ EHLNOCPD_00503 ┆ 141  ┆ 125  ┆ 0.886525 ┆ 16.141844 ┆ 18.208    │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
└────────────┴───────────────────┴────────────────┴──────┴──────┴──────────┴───────────┴───────────┘

In [4]:
# Read them all in!
filenames = glob.glob(f"{DIR}/*.depth.txt")

dflist = []
for i, n in enumerate(filenames):
    if i % 100 == 0:
        print(f"{i} of {len(filenames)}")
    n = os.path.basename(n)
    metag, _, species, _ = n.split('.', 3)
    dflist.append(read_depth_txt(metag, species))

depth_df = pl.concat(dflist)

print(f"read {len(filenames)} depth files.")

0 of 1753
100 of 1753
200 of 1753
300 of 1753
400 of 1753
500 of 1753
600 of 1753
700 of 1753
800 of 1753
900 of 1753
1000 of 1753
1100 of 1753
1200 of 1753
1300 of 1753
1400 of 1753
1500 of 1753
1600 of 1753
1700 of 1753
read 1753 depth files.

In [5]:
depth_df.filter(pl.col('depth_all').is_not_nan()).sort(by='depth_all', descending=True).filter(pl.col('depth_all') > 0.0)

shape: (181_875, 8)
┌─────────────┬──────────────┬──────────────┬──────┬──────┬──────────┬──────────────┬──────────────┐
│ metag       ┆ species      ┆ gene         ┆ len  ┆ hits ┆ breadth  ┆ depth_all    ┆ depth_cov    │
│ ---         ┆ ---          ┆ ---          ┆ ---  ┆ ---  ┆ ---      ┆ ---          ┆ ---          │
│ str         ┆ str          ┆ str          ┆ u32  ┆ u32  ┆ f64      ┆ f64          ┆ f64          │
╞═════════════╪══════════════╪══════════════╪══════╪══════╪══════════╪══════════════╪══════════════╡
│ SRR17241520 ┆ s__Sodaliphi ┆ JHPFMEME_009 ┆ 702  ┆ 702  ┆ 1.0      ┆ 48573.501425 ┆ 48573.501425 │
│             ┆ lus          ┆ 05           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp004557565  ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR17241677 ┆ s__Sodaliphi ┆ JHPFMEME_009 ┆ 702  ┆ 702  ┆ 1.0      ┆ 44080.032764 ┆ 44080.032764 │
│             ┆ lus          ┆ 05           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp004557565  ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR17241632 ┆ s__Sodaliphi ┆ JHPFMEME_009 ┆ 702  ┆ 702  ┆ 1.0      ┆ 30802.037037 ┆ 30802.037037 │
│             ┆ lus          ┆ 05           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp004557565  ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR17241654 ┆ s__Sodaliphi ┆ JHPFMEME_009 ┆ 702  ┆ 702  ┆ 1.0      ┆ 27947.760684 ┆ 27947.760684 │
│             ┆ lus          ┆ 05           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp004557565  ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR17241672 ┆ s__Sodaliphi ┆ JHPFMEME_009 ┆ 702  ┆ 702  ┆ 1.0      ┆ 25236.007123 ┆ 25236.007123 │
│             ┆ lus          ┆ 05           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp004557565  ┆              ┆      ┆      ┆          ┆              ┆              │
│ …           ┆ …            ┆ …            ┆ …    ┆ …    ┆ …        ┆ …            ┆ …            │
│ SRR11185261 ┆ s__Sodaliphi ┆ EOMKCHNH_021 ┆ 1290 ┆ 2    ┆ 0.00155  ┆ 0.00155      ┆ 1.0          │
│             ┆ lus          ┆ 37           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp004557565  ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR16235689 ┆ s__Prevotell ┆ JKBOFALP_017 ┆ 2001 ┆ 3    ┆ 0.001499 ┆ 0.001499     ┆ 1.0          │
│             ┆ a            ┆ 20           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp002251295  ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR17241643 ┆ s__Prevotell ┆ KJGAGFBO_010 ┆ 2091 ┆ 3    ┆ 0.001435 ┆ 0.001435     ┆ 1.0          │
│             ┆ a            ┆ 44           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp000434975  ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR17241490 ┆ s__UBA2868   ┆ PCFNEHJA_018 ┆ 936  ┆ 1    ┆ 0.001068 ┆ 0.001068     ┆ 1.0          │
│             ┆ sp004552595  ┆ 10           ┆      ┆      ┆          ┆              ┆              │
│ SRR8960802  ┆ s__Sodaliphi ┆ FCPBIAPK_019 ┆ 4674 ┆ 2    ┆ 0.000428 ┆ 0.000428     ┆ 1.0          │
│             ┆ lus          ┆ 98           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp004557565  ┆              ┆      ┆      ┆          ┆              ┆              │
└─────────────┴──────────────┴──────────────┴──────┴──────┴──────────┴──────────────┴──────────────┘

## Export mapping abundance data to a CSV, after merging with `species-genes.csv`

In [6]:
species_genes_df = (pl.read_csv('../outputs.cds/singleclust/species-genes.csv')
    .filter(pl.col("good") == 1)
    .with_columns(pl.col('gene_name').alias('gene'))
    .select(["anchor", "gene", "species", "description"])
)

species_genes_df

shape: (69, 4)
┌────────┬────────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ anchor ┆ gene           ┆ species                         ┆ description                     │
│ ---    ┆ ---            ┆ ---                             ┆ ---                             │
│ i64    ┆ str            ┆ str                             ┆ str                             │
╞════════╪════════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ 1      ┆ CNENGHLA_01260 ┆ s__Phascolarctobacterium_A suc… ┆ BLAST match to hydrogenase lar… │
│ 0      ┆ EHOAPHDI_01174 ┆ s__Phascolarctobacterium_A suc… ┆ BLAST match to protein phospha… │
│ 0      ┆ CNENGHLA_00658 ┆ s__Phascolarctobacterium_A suc… ┆ BLAST match to 4-hydroxy-3-met… │
│ 0      ┆ IFIBFMPA_00800 ┆ s__Phascolarctobacterium_A suc… ┆ BLAST match to  2-isopropylmal… │
│ 0      ┆ BBOFCOCJ_01349 ┆ s__Lactobacillus amylovorus     ┆ BLAST match to peptidase T [La… │
│ …      ┆ …              ┆ …                               ┆ …                               │
│ 1      ┆ JBPBJODD_00501 ┆ s__Cryptobacteroides sp0004349… ┆ hypothetical protein [Bacteroi… │
│ 0      ┆ KHMCBGLI_01458 ┆ s__Cryptobacteroides sp0004349… ┆ putative uncharacterized prote… │
│ 0      ┆ FCHBMNJF_01297 ┆ s__Cryptobacteroides sp0004349… ┆ ATP-binding protein [Bacteroid… │
│ 1      ┆ IIAENJBH_00799 ┆ s__Floccifex porci              ┆ anaerobic ribonucleoside-triph… │
│ 1      ┆ JBNOCHBL_00669 ┆ s__Fimisoma sp002320005         ┆ PEP/pyruvate-binding domain-co… │
└────────┴────────────────┴─────────────────────────────────┴─────────────────────────────────┘

In [7]:
merge_df = depth_df.join(species_genes_df, on=["species", "gene"], how='inner')
merge_df

shape: (7_131, 10)
┌─────────────┬─────────────┬─────────────┬──────┬───┬───────────┬───────────┬────────┬────────────┐
│ metag       ┆ species     ┆ gene        ┆ len  ┆ … ┆ depth_all ┆ depth_cov ┆ anchor ┆ descriptio │
│ ---         ┆ ---         ┆ ---         ┆ ---  ┆   ┆ ---       ┆ ---       ┆ ---    ┆ n          │
│ str         ┆ str         ┆ str         ┆ u32  ┆   ┆ f64       ┆ f64       ┆ i64    ┆ ---        │
│             ┆             ┆             ┆      ┆   ┆           ┆           ┆        ┆ str        │
╞═════════════╪═════════════╪═════════════╪══════╪═══╪═══════════╪═══════════╪════════╪════════════╡
│ SRR8960206  ┆ s__Floccife ┆ IIAENJBH_00 ┆ 1848 ┆ … ┆ 0.511905  ┆ 1.192938  ┆ 1      ┆ anaerobic  │
│             ┆ x porci     ┆ 799         ┆      ┆   ┆           ┆           ┆        ┆ ribonucleo │
│             ┆             ┆             ┆      ┆   ┆           ┆           ┆        ┆ side-triph │
│             ┆             ┆             ┆      ┆   ┆           ┆           ┆        ┆ …          │
│ SRR8960441  ┆ s__Cryptoba ┆ JBPBJODD_01 ┆ 1074 ┆ … ┆ 4.93203   ┆ 5.172852  ┆ 0      ┆ relA/SpoT  │
│             ┆ cteroides   ┆ 157         ┆      ┆   ┆           ┆           ┆        ┆ family     │
│             ┆ sp0004349…  ┆             ┆      ┆   ┆           ┆           ┆        ┆ protein    │
│             ┆             ┆             ┆      ┆   ┆           ┆           ┆        ┆ [Bac…      │
│ SRR8960441  ┆ s__Cryptoba ┆ KHMCBGLI_01 ┆ 1734 ┆ … ┆ 3.291811  ┆ 3.869831  ┆ 0      ┆ putative   │
│             ┆ cteroides   ┆ 458         ┆      ┆   ┆           ┆           ┆        ┆ uncharacte │
│             ┆ sp0004349…  ┆             ┆      ┆   ┆           ┆           ┆        ┆ rized      │
│             ┆             ┆             ┆      ┆   ┆           ┆           ┆        ┆ prote…     │
│ SRR8960441  ┆ s__Cryptoba ┆ JBPBJODD_00 ┆ 2034 ┆ … ┆ 5.193215  ┆ 5.571203  ┆ 1      ┆ hypothetic │
│             ┆ cteroides   ┆ 501         ┆      ┆   ┆           ┆           ┆        ┆ al protein │
│             ┆ sp0004349…  ┆             ┆      ┆   ┆           ┆           ┆        ┆ [Bacteroi… │
│ SRR8960441  ┆ s__Cryptoba ┆ FCHBMNJF_01 ┆ 3525 ┆ … ┆ 5.731915  ┆ 5.731915  ┆ 0      ┆ ATP-bindin │
│             ┆ cteroides   ┆ 297         ┆      ┆   ┆           ┆           ┆        ┆ g protein  │
│             ┆ sp0004349…  ┆             ┆      ┆   ┆           ┆           ┆        ┆ [Bacteroid │
│             ┆             ┆             ┆      ┆   ┆           ┆           ┆        ┆ …          │
│ …           ┆ …           ┆ …           ┆ …    ┆ … ┆ …         ┆ …         ┆ …      ┆ …          │
│ SRR17241640 ┆ s__Prevotel ┆ APOLKBKG_00 ┆ 3177 ┆ … ┆ 4.85395   ┆ 7.216191  ┆ 1      ┆ efflux RND │
│             ┆ la          ┆ 160         ┆      ┆   ┆           ┆           ┆        ┆ transporte │
│             ┆ sp000434975 ┆             ┆      ┆   ┆           ┆           ┆        ┆ r permeas… │
│ SRR17241640 ┆ s__Prevotel ┆ IGEONAAO_00 ┆ 423  ┆ … ┆ 6.219858  ┆ 10.119231 ┆ 0      ┆ hypothetic │
│             ┆ la          ┆ 273         ┆      ┆   ┆           ┆           ┆        ┆ al protein │
│             ┆ sp000434975 ┆             ┆      ┆   ┆           ┆           ┆        ┆            │
│ SRR18048908 ┆ s__Prevotel ┆ APOLKBKG_00 ┆ 3177 ┆ … ┆ 16.341832 ┆ 16.341832 ┆ 1      ┆ efflux RND │
│             ┆ la          ┆ 160         ┆      ┆   ┆           ┆           ┆        ┆ transporte │
│             ┆ sp000434975 ┆             ┆      ┆   ┆           ┆           ┆        ┆ r permeas… │
│ SRR18048908 ┆ s__Prevotel ┆ IGEONAAO_00 ┆ 423  ┆ … ┆ 12.491726 ┆ 17.438944 ┆ 0      ┆ hypothetic │
│             ┆ la          ┆ 273         ┆      ┆   ┆           ┆           ┆        ┆ al protein │
│             ┆ sp000434975 ┆             ┆      ┆   ┆           ┆           ┆        ┆            │
│ SRR18048908 ┆ s__Prevotel ┆ IAFAPFAC_01 ┆ 783  ┆ … ┆ 13.075351 ┆ 13.075351 ┆ 0      ┆ hypothetic │
│             ┆ la          ┆ 635         ┆      ┆   ┆           ┆           ┆        ┆ al protein │
│             ┆ sp000434975 ┆             ┆      ┆   ┆           ┆           ┆        ┆            │
└─────────────┴─────────────┴─────────────┴──────┴───┴───────────┴───────────┴────────┴────────────┘

In [8]:
merge_df.write_csv('../outputs.cds/cds3-genes/mapping-coverage-highcov-metag.csv')

In [9]:
print(len(merge_df))
print(len(species_genes_df))

7131
69

In [10]:
species_genes_df['gene'].n_unique()

69

In [11]:
merge_df['gene'].n_unique()

61