# Look at mapping breadth and depth of 100 x metagenomes to singleclust genes

In [1]:
import polars as pl
import glob
import os
import screed
import csv
import screed

## Read in individual metag x species singleclust depth reports

These files contain depth-of-mapping information for all our genes.

In [2]:
DIR='../outputs.cds/singleclust/bam.bak'
template = '../outputs.cds/singleclust/bam/{metag}.x.{species}.depth.txt'

def read_depth_txt(metag, species, *, exclude_ends=75):
    filename = template.format(metag=metag, species=species)
    df = pl.read_csv(filename, separator='\t', has_header=False,
                 new_columns=('gene', 'pos', 'cov', 'foo')).select(['gene', 'pos', 'cov'])

    sum_df = df.group_by('gene').all().with_columns(
        # select slice [75:-75]
        (pl.col("pos").list.slice(exclude_ends, -exclude_ends).list.len()).alias("len"),
        (pl.col("cov").list.slice(exclude_ends, -exclude_ends)),
        (pl.col("cov").list.slice(exclude_ends, -exclude_ends).list.filter(pl.element() > 0)).list.len().alias("hits"),
    ).with_columns(
        (pl.lit(metag).alias("metag")),
        (pl.lit(species).alias("species")),
        # summarize: average depth across contig,
        (pl.col("cov").list.sum() / pl.col("len")).alias("depth_all"),
        # average depth across covered bases,
        (pl.col("cov").list.sum() / pl.col("hits")).alias("depth_cov"),
        # fraction of bases covered
        (pl.col("hits") / pl.col("cov").list.len()).alias("breadth"),
    ).select(["metag", "species", "gene", "len", "hits", "breadth", "depth_all", "depth_cov"])
    return sum_df

read_depth_txt('ERR1135199', 's__Cryptobacteroides sp900546925')

shape: (248, 8)
┌────────────┬───────────────────┬────────────────┬──────┬──────┬──────────┬───────────┬───────────┐
│ metag      ┆ species           ┆ gene           ┆ len  ┆ hits ┆ breadth  ┆ depth_all ┆ depth_cov │
│ ---        ┆ ---               ┆ ---            ┆ ---  ┆ ---  ┆ ---      ┆ ---       ┆ ---       │
│ str        ┆ str               ┆ str            ┆ u32  ┆ u32  ┆ f64      ┆ f64       ┆ f64       │
╞════════════╪═══════════════════╪════════════════╪══════╪══════╪══════════╪═══════════╪═══════════╡
│ ERR1135199 ┆ s__Cryptobacteroi ┆ GIIIOOFK_00161 ┆ 930  ┆ 0    ┆ 0.0      ┆ 0.0       ┆ NaN       │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ ELJKHIPJ_00342 ┆ 339  ┆ 222  ┆ 0.654867 ┆ 1.079646  ┆ 1.648649  │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ LELOEEPG_00778 ┆ 435  ┆ 317  ┆ 0.728736 ┆ 1.045977  ┆ 1.435331  │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ FNIGJHLI_01182 ┆ 1542 ┆ 1087 ┆ 0.704929 ┆ 1.389105  ┆ 1.970561  │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ CPBNAKKL_00323 ┆ 561  ┆ 392  ┆ 0.698752 ┆ 1.135472  ┆ 1.625     │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ …          ┆ …                 ┆ …              ┆ …    ┆ …    ┆ …        ┆ …         ┆ …         │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ KJEHENCE_01089 ┆ 894  ┆ 479  ┆ 0.535794 ┆ 0.536913  ┆ 1.002088  │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ ELKPFNCN_00187 ┆ 870  ┆ 0    ┆ 0.0      ┆ 0.0       ┆ NaN       │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ BNDPAENK_00069 ┆ 1212 ┆ 1076 ┆ 0.887789 ┆ 2.096535  ┆ 2.361524  │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ HGGDIOJJ_00633 ┆ 258  ┆ 258  ┆ 1.0      ┆ 2.046512  ┆ 2.046512  │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ KICIJKOM_00206 ┆ 618  ┆ 189  ┆ 0.305825 ┆ 0.346278  ┆ 1.132275  │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
└────────────┴───────────────────┴────────────────┴──────┴──────┴──────────┴───────────┴───────────┘

In [3]:
# Read them all in!
filenames = glob.glob(f"{DIR}/*.depth.txt")

dflist = []
for i, n in enumerate(filenames):
    if i % 100 == 0:
        print(f"{i} of {len(filenames)}")
    n = os.path.basename(n)
    metag, _, species, _ = n.split('.', 3)
    dflist.append(read_depth_txt(metag, species))

depth_df = pl.concat(dflist)

print(f"read {len(filenames)} depth files.")

0 of 1400
100 of 1400
200 of 1400
300 of 1400
400 of 1400
500 of 1400
600 of 1400
700 of 1400
800 of 1400
900 of 1400
1000 of 1400
1100 of 1400
1200 of 1400
1300 of 1400
read 1400 depth files.

In [4]:
depth_df.filter(pl.col('depth_all').is_not_nan()).sort(by='depth_all', descending=True).filter(pl.col('depth_all') > 0.0)

shape: (118_345, 8)
┌─────────────┬──────────────┬──────────────┬──────┬──────┬──────────┬──────────────┬──────────────┐
│ metag       ┆ species      ┆ gene         ┆ len  ┆ hits ┆ breadth  ┆ depth_all    ┆ depth_cov    │
│ ---         ┆ ---          ┆ ---          ┆ ---  ┆ ---  ┆ ---      ┆ ---          ┆ ---          │
│ str         ┆ str          ┆ str          ┆ u32  ┆ u32  ┆ f64      ┆ f64          ┆ f64          │
╞═════════════╪══════════════╪══════════════╪══════╪══════╪══════════╪══════════════╪══════════════╡
│ SRR14369134 ┆ s__Sodaliphi ┆ JHPFMEME_009 ┆ 702  ┆ 702  ┆ 1.0      ┆ 17800.038462 ┆ 17800.038462 │
│             ┆ lus          ┆ 05           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp004557565  ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR11489750 ┆ s__Sodaliphi ┆ JHPFMEME_009 ┆ 702  ┆ 702  ┆ 1.0      ┆ 12280.894587 ┆ 12280.894587 │
│             ┆ lus          ┆ 05           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp004557565  ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR12795790 ┆ s__Sodaliphi ┆ JHPFMEME_009 ┆ 702  ┆ 702  ┆ 1.0      ┆ 8948.836182  ┆ 8948.836182  │
│             ┆ lus          ┆ 05           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp004557565  ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR10209683 ┆ s__Mogibacte ┆ AAOFCIJB_002 ┆ 1119 ┆ 1119 ┆ 1.0      ┆ 8170.679178  ┆ 8170.679178  │
│             ┆ rium_A       ┆ 77           ┆      ┆      ┆          ┆              ┆              │
│             ┆ kristiansen… ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR17241663 ┆ s__Mogibacte ┆ JMKEGFFJ_013 ┆ 1899 ┆ 1899 ┆ 1.0      ┆ 7469.317536  ┆ 7469.317536  │
│             ┆ rium_A       ┆ 26           ┆      ┆      ┆          ┆              ┆              │
│             ┆ kristiansen… ┆              ┆      ┆      ┆          ┆              ┆              │
│ …           ┆ …            ┆ …            ┆ …    ┆ …    ┆ …        ┆ …            ┆ …            │
│ ERR3211876  ┆ s__Gemmiger  ┆ PMKFNJDI_004 ┆ 3072 ┆ 4    ┆ 0.001302 ┆ 0.001302     ┆ 1.0          │
│             ┆ qucibialis   ┆ 77           ┆      ┆      ┆          ┆              ┆              │
│ SRR8655118  ┆ s__Cryptobac ┆ CMHHCIHA_008 ┆ 2016 ┆ 2    ┆ 0.000992 ┆ 0.000992     ┆ 1.0          │
│             ┆ teroides     ┆ 93           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp9005469…   ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR11124687 ┆ s__Prevotell ┆ OPHKNFIJ_008 ┆ 2094 ┆ 2    ┆ 0.000955 ┆ 0.000955     ┆ 1.0          │
│             ┆ a            ┆ 63           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp002251295  ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR14369255 ┆ s__Cryptobac ┆ OIJDNDLK_007 ┆ 1074 ┆ 1    ┆ 0.000931 ┆ 0.000931     ┆ 1.0          │
│             ┆ teroides     ┆ 02           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp9005469…   ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR11126273 ┆ s__UBA2868   ┆ BJBPFFKB_014 ┆ 3480 ┆ 1    ┆ 0.000287 ┆ 0.000287     ┆ 1.0          │
│             ┆ sp004552595  ┆ 40           ┆      ┆      ┆          ┆              ┆              │
└─────────────┴──────────────┴──────────────┴──────┴──────┴──────────┴──────────────┴──────────────┘

## Summarize our mapping breadth results across all the metagenomes

In [5]:
# require 10% of each gene to be covered by at least one read
BREADTH_CUTOFF = 0.1

In [6]:
# aggregate across all metagenomes;
# calculate fraction of metagenomes for which gene mapping exceeds our breadth cutoff
agg_df = depth_df.group_by(['species', 'gene']).agg(
    # get fraction of columns where breadth is greater than cutoff as 'f'
    ((pl.col("breadth") >= BREADTH_CUTOFF).sum() / pl.col("breadth").len()).alias("f"),
#    (pl.col("depth").filter(pl.col("depth").is_not_nan()).mean()),
)
agg_df

shape: (1_449, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Sodaliphilus sp004557565     ┆ NINKMKKC_00022 ┆ 0.79 │
│ s__Cryptobacteroides sp9005469… ┆ BEKEPKDC_01232 ┆ 0.82 │
│ s__Sodaliphilus sp004557565     ┆ FLLLPNHA_00844 ┆ 0.65 │
│ s__Cryptobacteroides sp9005469… ┆ BEKEPKDC_00394 ┆ 0.84 │
│ s__Cryptobacteroides sp9005469… ┆ MFHJPMDA_00569 ┆ 0.38 │
│ …                               ┆ …              ┆ …    │
│ s__Cryptobacteroides sp9005469… ┆ CPBNAKKL_00778 ┆ 0.85 │
│ s__Prevotella sp002251295       ┆ OJEBGNEI_00601 ┆ 0.84 │
│ s__Sodaliphilus sp004557565     ┆ EDCDMAMI_01817 ┆ 0.91 │
│ s__Sodaliphilus sp004557565     ┆ GPAFGJJE_00089 ┆ 0.92 │
│ s__Prevotella sp000434975       ┆ OKGFALME_00303 ┆ 0.78 │
└─────────────────────────────────┴────────────────┴──────┘

In [7]:
# print information out by species
for species in sorted(agg_df['species'].unique()):
    print(species)
    foo_df = agg_df.filter(pl.col("species") == species)
    foo_df = foo_df.sort(by='f', descending=True).filter(pl.col('f') > 0.8)
    print(foo_df)

    top50_names = set(foo_df.head(50)['gene'].to_list())

    outfile = f'../outputs.cds/singleclust/{species}.cds.min50.dedup.top50.fa'
    print(outfile)
    outfp = open(outfile, 'wt')
    for record in screed.open(f'../outputs.cds/singleclust/{species}.cds3.min50.dedup.fa'):
        name = record.name.split(' ')[0]
        if name in top50_names:
            top50_names.remove(name)
            outfp.write(f'>{record.name}\n{record.sequence}\n')
    assert not top50_names
    outfp.close()

    outfile2 = f'../outputs.cds/singleclust/{species}.cds.min50.dedup.top50.csv'
    print(outfile2)
    outfp = open(outfile2, 'w', newline='')
    w = csv.writer(outfp)

    for name in foo_df.head(50)['gene'].to_list():
        w.writerow(['0', species, name, "(not reviewed)"])
    outfp.close()

s__Bariatricus sp004560705
shape: (14, 3)
┌────────────────────────────┬────────────────┬──────┐
│ species                    ┆ gene           ┆ f    │
│ ---                        ┆ ---            ┆ ---  │
│ str                        ┆ str            ┆ f64  │
╞════════════════════════════╪════════════════╪══════╡
│ s__Bariatricus sp004560705 ┆ CHOLCMOC_00863 ┆ 0.97 │
│ s__Bariatricus sp004560705 ┆ LEHFNBLN_00701 ┆ 0.95 │
│ s__Bariatricus sp004560705 ┆ LEHFNBLN_02301 ┆ 0.93 │
│ s__Bariatricus sp004560705 ┆ NDCIOGGG_00214 ┆ 0.9  │
│ s__Bariatricus sp004560705 ┆ FMMMFAAO_00746 ┆ 0.89 │
│ …                          ┆ …              ┆ …    │
│ s__Bariatricus sp004560705 ┆ NOACAEKI_00860 ┆ 0.82 │
│ s__Bariatricus sp004560705 ┆ IEPLHDOE_02248 ┆ 0.82 │
│ s__Bariatricus sp004560705 ┆ EMNHIHKA_01693 ┆ 0.82 │
│ s__Bariatricus sp004560705 ┆ ELOEBFJM_01459 ┆ 0.81 │
│ s__Bariatricus sp004560705 ┆ NGBMPMHL_00028 ┆ 0.81 │
└────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Bariatricus sp004560705.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Bariatricus sp004560705.cds.min50.dedup.top50.csv
s__Cryptobacteroides sp900546925
shape: (117, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Cryptobacteroides sp9005469… ┆ FIKGMHDC_00998 ┆ 0.94 │
│ s__Cryptobacteroides sp9005469… ┆ CMHHCIHA_00622 ┆ 0.92 │
│ s__Cryptobacteroides sp9005469… ┆ BDFOMKKK_00335 ┆ 0.92 │
│ s__Cryptobacteroides sp9005469… ┆ BEKEPKDC_00417 ┆ 0.9  │
│ s__Cryptobacteroides sp9005469… ┆ EHLNOCPD_00288 ┆ 0.89 │
│ …                               ┆ …              ┆ …    │
│ s__Cryptobacteroides sp9005469… ┆ FOKFIHIM_00492 ┆ 0.81 │
│ s__Cryptobacteroides sp9005469… ┆ IKEOPBPE_00959 ┆ 0.81 │
│ s__Cryptobacteroides sp9005469… ┆ IEFFFPKJ_00327 ┆ 0.81 │
│ s__Cryptobacteroides sp9005469… ┆ LELOEEPG_00242 ┆ 0.81 │
│ s__Cryptobacteroides sp9005469… ┆ OIJDNDLK_01388 ┆ 0.81 │
└─────────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Cryptobacteroides sp900546925.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Cryptobacteroides sp900546925.cds.min50.dedup.top50.csv
s__Fimisoma sp002320005
shape: (1, 3)
┌─────────────────────────┬────────────────┬──────┐
│ species                 ┆ gene           ┆ f    │
│ ---                     ┆ ---            ┆ ---  │
│ str                     ┆ str            ┆ f64  │
╞═════════════════════════╪════════════════╪══════╡
│ s__Fimisoma sp002320005 ┆ JAOEKFJL_01590 ┆ 0.92 │
└─────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Fimisoma sp002320005.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Fimisoma sp002320005.cds.min50.dedup.top50.csv
s__Gemmiger qucibialis
shape: (10, 3)
┌────────────────────────┬────────────────┬──────┐
│ species                ┆ gene           ┆ f    │
│ ---                    ┆ ---            ┆ ---  │
│ str                    ┆ str            ┆ f64  │
╞════════════════════════╪════════════════╪══════╡
│ s__Gemmiger qucibialis ┆ GLIPJGEI_00065 ┆ 0.94 │
│ s__Gemmiger qucibialis ┆ EANOHOOJ_01559 ┆ 0.92 │
│ s__Gemmiger qucibialis ┆ IPGJNJJC_00242 ┆ 0.91 │
│ s__Gemmiger qucibialis ┆ CLHLFGFN_00542 ┆ 0.91 │
│ s__Gemmiger qucibialis ┆ LAOGNEID_00570 ┆ 0.9  │
│ s__Gemmiger qucibialis ┆ AGHFCGHF_02266 ┆ 0.89 │
│ s__Gemmiger qucibialis ┆ DLCICKOP_02020 ┆ 0.85 │
│ s__Gemmiger qucibialis ┆ GOPMMJLD_01454 ┆ 0.85 │
│ s__Gemmiger qucibialis ┆ PEAPMGON_00222 ┆ 0.82 │
│ s__Gemmiger qucibialis ┆ EBFKGAGP_00060 ┆ 0.81 │
└────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Gemmiger qucibialis.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Gemmiger qucibialis.cds.min50.dedup.top50.csv
s__Holdemanella porci
shape: (0, 3)
┌─────────┬──────┬─────┐
│ species ┆ gene ┆ f   │
│ ---     ┆ ---  ┆ --- │
│ str     ┆ str  ┆ f64 │
╞═════════╪══════╪═════╡
└─────────┴──────┴─────┘
../outputs.cds/singleclust/s__Holdemanella porci.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Holdemanella porci.cds.min50.dedup.top50.csv
s__JALFVM01 sp022787145
shape: (0, 3)
┌─────────┬──────┬─────┐
│ species ┆ gene ┆ f   │
│ ---     ┆ ---  ┆ --- │
│ str     ┆ str  ┆ f64 │
╞═════════╪══════╪═════╡
└─────────┴──────┴─────┘
../outputs.cds/singleclust/s__JALFVM01 sp022787145.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__JALFVM01 sp022787145.cds.min50.dedup.top50.csv
s__Lactobacillus amylovorus
shape: (18, 3)
┌─────────────────────────────┬────────────────┬──────┐
│ species                     ┆ gene           ┆ f    │
│ ---                         ┆ ---            ┆ ---  │
│ str                         ┆ str            ┆ f64  │
╞═════════════════════════════╪════════════════╪══════╡
│ s__Lactobacillus amylovorus ┆ CPLGDGDL_01434 ┆ 0.92 │
│ s__Lactobacillus amylovorus ┆ BBOFCOCJ_01349 ┆ 0.9  │
│ s__Lactobacillus amylovorus ┆ HPBCBKPJ_01887 ┆ 0.89 │
│ s__Lactobacillus amylovorus ┆ PGPELEHO_01832 ┆ 0.87 │
│ s__Lactobacillus amylovorus ┆ OBGMJDLM_01221 ┆ 0.87 │
│ …                           ┆ …              ┆ …    │
│ s__Lactobacillus amylovorus ┆ CPKOPDLF_00550 ┆ 0.82 │
│ s__Lactobacillus amylovorus ┆ POPGAILL_01491 ┆ 0.82 │
│ s__Lactobacillus amylovorus ┆ LEAIKLIG_01457 ┆ 0.81 │
│ s__Lactobacillus amylovorus ┆ NKKPHFMM_01729 ┆ 0.81 │
│ s__Lactobacillus amylovorus ┆ IAOGNCPA_00195 ┆ 0.81 │
└─────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Lactobacillus amylovorus.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Lactobacillus amylovorus.cds.min50.dedup.top50.csv
s__Mogibacterium_A kristiansenii
shape: (3, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Mogibacterium_A kristiansen… ┆ AAOFCIJB_00277 ┆ 1.0  │
│ s__Mogibacterium_A kristiansen… ┆ JMKEGFFJ_01326 ┆ 1.0  │
│ s__Mogibacterium_A kristiansen… ┆ NGANNMPO_01097 ┆ 0.87 │
└─────────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Mogibacterium_A kristiansenii.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Mogibacterium_A kristiansenii.cds.min50.dedup.top50.csv
s__Phascolarctobacterium_A succinatutens
shape: (5, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Phascolarctobacterium_A suc… ┆ CNENGHLA_00658 ┆ 0.96 │
│ s__Phascolarctobacterium_A suc… ┆ CNENGHLA_01260 ┆ 0.91 │
│ s__Phascolarctobacterium_A suc… ┆ LDBAILDD_01769 ┆ 0.9  │
│ s__Phascolarctobacterium_A suc… ┆ GGLHANJG_01414 ┆ 0.88 │
│ s__Phascolarctobacterium_A suc… ┆ DHJLCIIK_01145 ┆ 0.84 │
└─────────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Phascolarctobacterium_A succinatutens.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Phascolarctobacterium_A succinatutens.cds.min50.dedup.top50.csv
s__Prevotella sp000434975
shape: (75, 3)
┌───────────────────────────┬────────────────┬──────┐
│ species                   ┆ gene           ┆ f    │
│ ---                       ┆ ---            ┆ ---  │
│ str                       ┆ str            ┆ f64  │
╞═══════════════════════════╪════════════════╪══════╡
│ s__Prevotella sp000434975 ┆ HGGBKJHA_00064 ┆ 0.93 │
│ s__Prevotella sp000434975 ┆ AJCJGFNH_00477 ┆ 0.93 │
│ s__Prevotella sp000434975 ┆ MLIECJNI_00172 ┆ 0.92 │
│ s__Prevotella sp000434975 ┆ BAIAEPON_01639 ┆ 0.92 │
│ s__Prevotella sp000434975 ┆ PDHLFJAL_00903 ┆ 0.92 │
│ …                         ┆ …              ┆ …    │
│ s__Prevotella sp000434975 ┆ LNBCJMFF_01780 ┆ 0.81 │
│ s__Prevotella sp000434975 ┆ JEAAMBOG_00279 ┆ 0.81 │
│ s__Prevotella sp000434975 ┆ DEENMOAI_01503 ┆ 0.81 │
│ s__Prevotella sp000434975 ┆ IBOOIAKE_00716 ┆ 0.81 │
│ s__Prevotella sp000434975 ┆ CHAJGCIB_01628 ┆ 0.81 │
└───────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Prevotella sp000434975.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Prevotella sp000434975.cds.min50.dedup.top50.csv
s__Prevotella sp002251295
shape: (77, 3)
┌───────────────────────────┬────────────────┬──────┐
│ species                   ┆ gene           ┆ f    │
│ ---                       ┆ ---            ┆ ---  │
│ str                       ┆ str            ┆ f64  │
╞═══════════════════════════╪════════════════╪══════╡
│ s__Prevotella sp002251295 ┆ IPDEFMND_01992 ┆ 0.95 │
│ s__Prevotella sp002251295 ┆ COCKKAPE_02026 ┆ 0.93 │
│ s__Prevotella sp002251295 ┆ KINAFDOL_01550 ┆ 0.92 │
│ s__Prevotella sp002251295 ┆ GFALEAHI_01277 ┆ 0.91 │
│ s__Prevotella sp002251295 ┆ HJAAFCJA_01737 ┆ 0.91 │
│ …                         ┆ …              ┆ …    │
│ s__Prevotella sp002251295 ┆ OAHOCONN_01297 ┆ 0.81 │
│ s__Prevotella sp002251295 ┆ KEAKGAAF_02352 ┆ 0.81 │
│ s__Prevotella sp002251295 ┆ OAHOCONN_01023 ┆ 0.81 │
│ s__Prevotella sp002251295 ┆ OEDAEGJB_01922 ┆ 0.81 │
│ s__Prevotella sp002251295 ┆ GDBLKLPM_00824 ┆ 0.81 │
└───────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Prevotella sp002251295.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Prevotella sp002251295.cds.min50.dedup.top50.csv
s__Roseburia inulinivorans
shape: (4, 3)
┌────────────────────────────┬────────────────┬──────┐
│ species                    ┆ gene           ┆ f    │
│ ---                        ┆ ---            ┆ ---  │
│ str                        ┆ str            ┆ f64  │
╞════════════════════════════╪════════════════╪══════╡
│ s__Roseburia inulinivorans ┆ HGAHBKMD_00300 ┆ 0.84 │
│ s__Roseburia inulinivorans ┆ HGAHBKMD_00299 ┆ 0.83 │
│ s__Roseburia inulinivorans ┆ HGAHBKMD_00261 ┆ 0.83 │
│ s__Roseburia inulinivorans ┆ HGAHBKMD_00273 ┆ 0.81 │
└────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Roseburia inulinivorans.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Roseburia inulinivorans.cds.min50.dedup.top50.csv
s__Sodaliphilus sp004557565
shape: (497, 3)
┌─────────────────────────────┬────────────────┬──────┐
│ species                     ┆ gene           ┆ f    │
│ ---                         ┆ ---            ┆ ---  │
│ str                         ┆ str            ┆ f64  │
╞═════════════════════════════╪════════════════╪══════╡
│ s__Sodaliphilus sp004557565 ┆ JHPFMEME_00905 ┆ 0.98 │
│ s__Sodaliphilus sp004557565 ┆ HENFICJG_01772 ┆ 0.96 │
│ s__Sodaliphilus sp004557565 ┆ MPEKMBOO_01380 ┆ 0.96 │
│ s__Sodaliphilus sp004557565 ┆ JJHEGIOA_01813 ┆ 0.96 │
│ s__Sodaliphilus sp004557565 ┆ COJGPLPN_01769 ┆ 0.96 │
│ …                           ┆ …              ┆ …    │
│ s__Sodaliphilus sp004557565 ┆ OLAJAFEB_01647 ┆ 0.81 │
│ s__Sodaliphilus sp004557565 ┆ LFLAOHMB_01227 ┆ 0.81 │
│ s__Sodaliphilus sp004557565 ┆ MKOAJGNL_01972 ┆ 0.81 │
│ s__Sodaliphilus sp004557565 ┆ GEGNICLP_00271 ┆ 0.81 │
│ s__Sodaliphilus sp004557565 ┆ JPBNNJKP_01057 ┆ 0.81 │
└─────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Sodaliphilus sp004557565.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Sodaliphilus sp004557565.cds.min50.dedup.top50.csv
s__UBA2868 sp004552595
shape: (5, 3)
┌────────────────────────┬────────────────┬──────┐
│ species                ┆ gene           ┆ f    │
│ ---                    ┆ ---            ┆ ---  │
│ str                    ┆ str            ┆ f64  │
╞════════════════════════╪════════════════╪══════╡
│ s__UBA2868 sp004552595 ┆ GHILBDOG_00591 ┆ 0.97 │
│ s__UBA2868 sp004552595 ┆ KMEHCMKH_00746 ┆ 0.88 │
│ s__UBA2868 sp004552595 ┆ GLNAKBGL_01080 ┆ 0.82 │
│ s__UBA2868 sp004552595 ┆ IEHIAHIF_00466 ┆ 0.82 │
│ s__UBA2868 sp004552595 ┆ IPIMNMMB_00240 ┆ 0.82 │
└────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__UBA2868 sp004552595.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__UBA2868 sp004552595.cds.min50.dedup.top50.csv

## Explore specific gene/species/metag combinations

In [8]:
depth_df.filter((pl.col("gene") == 'EHOAPHDI_01174')).sort(by='breadth')

shape: (0, 8)
┌───────┬─────────┬──────┬─────┬──────┬─────────┬───────────┬───────────┐
│ metag ┆ species ┆ gene ┆ len ┆ hits ┆ breadth ┆ depth_all ┆ depth_cov │
│ ---   ┆ ---     ┆ ---  ┆ --- ┆ ---  ┆ ---     ┆ ---       ┆ ---       │
│ str   ┆ str     ┆ str  ┆ u32 ┆ u32  ┆ f64     ┆ f64       ┆ f64       │
╞═══════╪═════════╪══════╪═════╪══════╪═════════╪═══════════╪═══════════╡
└───────┴─────────┴──────┴─────┴──────┴─────────┴───────────┴───────────┘

In [9]:
depth_df.filter((pl.col("gene") == 'EHOAPHDI_01174')).sort(by='breadth').filter(pl.col("metag") == "ERR1135199")

shape: (0, 8)
┌───────┬─────────┬──────┬─────┬──────┬─────────┬───────────┬───────────┐
│ metag ┆ species ┆ gene ┆ len ┆ hits ┆ breadth ┆ depth_all ┆ depth_cov │
│ ---   ┆ ---     ┆ ---  ┆ --- ┆ ---  ┆ ---     ┆ ---       ┆ ---       │
│ str   ┆ str     ┆ str  ┆ u32 ┆ u32  ┆ f64     ┆ f64       ┆ f64       │
╞═══════╪═════════╪══════╪═════╪══════╪═════════╪═══════════╪═══════════╡
└───────┴─────────┴──────┴─────┴──────┴─────────┴───────────┴───────────┘

## Try something else

In [10]:
names = set()
for filename in glob.glob('../outputs.cds/cds3-genes/*.fa'):
    names.update([ record.name.split(' ')[0] for record in screed.open(filename) ])
names

{'AIEIMHOC_00182',
 'AKLOHKAG_01416',
 'APOLKBKG_00160',
 'BBOFCOCJ_01349',
 'BHHJJAAP_00933',
 'CHOLCMOC_00863',
 'CMHHCIHA_00622',
 'CNENGHLA_00658',
 'CNENGHLA_01260',
 'COCKKAPE_02026',
 'DAPDNANK_01228',
 'DKAPMIEG_00121',
 'EBLLCBKE_00022',
 'EHOAPHDI_01174',
 'FGLPJJIK_03110',
 'FMBBPIHC_01435',
 'GFALEAHI_01277',
 'HJGGINOG_01324',
 'IAFAPFAC_01635',
 'IEPMJGAI_00771',
 'IFIBFMPA_00800',
 'IGEONAAO_00273',
 'JDFEBBFI_00464',
 'KINAFDOL_01550',
 'KPACIEHJ_00390',
 'LEHFNBLN_02301',
 'LJHBCGLM_01294',
 'MMBDDDLD_00384',
 'MNKNIMJG_02022',
 'NADIOELI_00170',
 'NLNOELNI_01902',
 'NMJBBHDE_00624',
 'OBGMJDLM_01221',
 'OIGHMFGK_00345',
 'OMBJBIHD_01711',
 'PKGEEMPI_00758'}

In [11]:
depth_df.filter(pl.col("gene").is_in(names)).sort(by='depth_all')

shape: (3_200, 8)
┌─────────────┬───────────────┬───────────────┬──────┬──────┬──────────┬─────────────┬─────────────┐
│ metag       ┆ species       ┆ gene          ┆ len  ┆ hits ┆ breadth  ┆ depth_all   ┆ depth_cov   │
│ ---         ┆ ---           ┆ ---           ┆ ---  ┆ ---  ┆ ---      ┆ ---         ┆ ---         │
│ str         ┆ str           ┆ str           ┆ u32  ┆ u32  ┆ f64      ┆ f64         ┆ f64         │
╞═════════════╪═══════════════╪═══════════════╪══════╪══════╪══════════╪═════════════╪═════════════╡
│ ERR1135199  ┆ s__Mogibacter ┆ LJHBCGLM_0129 ┆ 393  ┆ 0    ┆ 0.0      ┆ 0.0         ┆ NaN         │
│             ┆ ium_A         ┆ 4             ┆      ┆      ┆          ┆             ┆             │
│             ┆ kristiansen…  ┆               ┆      ┆      ┆          ┆             ┆             │
│ ERR1135199  ┆ s__Mogibacter ┆ AKLOHKAG_0141 ┆ 603  ┆ 0    ┆ 0.0      ┆ 0.0         ┆ NaN         │
│             ┆ ium_A         ┆ 6             ┆      ┆      ┆          ┆             ┆             │
│             ┆ kristiansen…  ┆               ┆      ┆      ┆          ┆             ┆             │
│ ERR1135199  ┆ s__Mogibacter ┆ BHHJJAAP_0093 ┆ 531  ┆ 0    ┆ 0.0      ┆ 0.0         ┆ NaN         │
│             ┆ ium_A         ┆ 3             ┆      ┆      ┆          ┆             ┆             │
│             ┆ kristiansen…  ┆               ┆      ┆      ┆          ┆             ┆             │
│ SRR11124687 ┆ s__Lactobacil ┆ OMBJBIHD_0171 ┆ 1134 ┆ 0    ┆ 0.0      ┆ 0.0         ┆ NaN         │
│             ┆ lus           ┆ 1             ┆      ┆      ┆          ┆             ┆             │
│             ┆ amylovorus    ┆               ┆      ┆      ┆          ┆             ┆             │
│ SRR12795790 ┆ s__Sodaliphil ┆ NLNOELNI_0190 ┆ 1968 ┆ 0    ┆ 0.0      ┆ 0.0         ┆ NaN         │
│             ┆ us            ┆ 2             ┆      ┆      ┆          ┆             ┆             │
│             ┆ sp004557565   ┆               ┆      ┆      ┆          ┆             ┆             │
│ …           ┆ …             ┆ …             ┆ …    ┆ …    ┆ …        ┆ …           ┆ …           │
│ SRR10209683 ┆ s__Lactobacil ┆ OMBJBIHD_0171 ┆ 1134 ┆ 1130 ┆ 0.996473 ┆ 673.320106  ┆ 675.70354   │
│             ┆ lus           ┆ 1             ┆      ┆      ┆          ┆             ┆             │
│             ┆ amylovorus    ┆               ┆      ┆      ┆          ┆             ┆             │
│ SRR10209683 ┆ s__Lactobacil ┆ OBGMJDLM_0122 ┆ 2574 ┆ 2574 ┆ 1.0      ┆ 706.990287  ┆ 706.990287  │
│             ┆ lus           ┆ 1             ┆      ┆      ┆          ┆             ┆             │
│             ┆ amylovorus    ┆               ┆      ┆      ┆          ┆             ┆             │
│ SRR17241521 ┆ s__Lactobacil ┆ BBOFCOCJ_0134 ┆ 1134 ┆ 990  ┆ 0.873016 ┆ 2054.869489 ┆ 2353.759596 │
│             ┆ lus           ┆ 9             ┆      ┆      ┆          ┆             ┆             │
│             ┆ amylovorus    ┆               ┆      ┆      ┆          ┆             ┆             │
│ SRR17241521 ┆ s__Lactobacil ┆ OBGMJDLM_0122 ┆ 2574 ┆ 2574 ┆ 1.0      ┆ 2958.051671 ┆ 2958.051671 │
│             ┆ lus           ┆ 1             ┆      ┆      ┆          ┆             ┆             │
│             ┆ amylovorus    ┆               ┆      ┆      ┆          ┆             ┆             │
│ SRR17241521 ┆ s__Lactobacil ┆ OMBJBIHD_0171 ┆ 1134 ┆ 1127 ┆ 0.993827 ┆ 3044.731922 ┆ 3063.643301 │
│             ┆ lus           ┆ 1             ┆      ┆      ┆          ┆             ┆             │
│             ┆ amylovorus    ┆               ┆      ┆      ┆          ┆             ┆             │
└─────────────┴───────────────┴───────────────┴──────┴──────┴──────────┴─────────────┴─────────────┘

In [12]:
depth_df.filter(pl.col("gene").is_in(names)).write_csv('../outputs.cds/cds3-genes/mapping-coverage.csv')