In [43]:
import polars as pl
import glob
import os

In [44]:
DIR='../outputs.mapping/cds3/outputs.singleclust'

In [49]:
template = '../outputs.mapping/cds3/outputs.singleclust/{metag}.x.{species}.depth.txt'

def read_depth(metag, species):
    filename = template.format(metag=metag, species=species)
    df = pl.read_csv(filename, separator='\t', has_header=False,
                 new_columns=('gene', 'pos', 'cov', 'foo'))
    sum_df = df.group_by('gene').agg(
        ((pl.col("cov") > 0).sum() / pl.col("pos").len()).alias("breadth")
    ).with_columns(
        (pl.lit(metag).alias("metag")),
        (pl.lit(species).alias("species"))
)
    return sum_df

read_depth('ERR1135199', 's__Cryptobacteroides sp900546925')

shape: (266, 4)
┌────────────────┬──────────┬────────────┬─────────────────────────────────┐
│ gene           ┆ breadth  ┆ metag      ┆ species                         │
│ ---            ┆ ---      ┆ ---        ┆ ---                             │
│ str            ┆ f64      ┆ str        ┆ str                             │
╞════════════════╪══════════╪════════════╪═════════════════════════════════╡
│ CPBNAKKL_01317 ┆ 0.461686 ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ PGBAIDML_01792 ┆ 0.0      ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ FNIGJHLI_00487 ┆ 0.0      ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ FNIGJHLI_00528 ┆ 0.506611 ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ BEKEPKDC_01021 ┆ 0.702721 ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ …              ┆ …        ┆ …          ┆ …                               │
│ BDFOMKKK_01862 ┆ 0.105691 ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ LHAJOBLP_00025 ┆ 0.933333 ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ IEFFFPKJ_00801 ┆ 0.546296 ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ FNIGJHLI_00556 ┆ 0.0      ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ HMMHNFMB_01134 ┆ 0.911111 ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
└────────────────┴──────────┴────────────┴─────────────────────────────────┘

In [47]:
filename = 'ERR1135199.x.s__Cryptobacteroides sp900546925.depth.txt'
filenames = glob.glob(f"{DIR}/*.depth.txt")

dflist = []
for i, n in enumerate(filenames):
    if i % 100 == 0:
        print(f"{i} of {len(filenames)}")
    n = os.path.basename(n)
    metag, _, species, _ = n.split('.', 3)
    dflist.append(read_depth(metag, species))

0 1400
100 1400
200 1400
300 1400
400 1400
500 1400
600 1400
700 1400
800 1400
900 1400
1000 1400
1100 1400
1200 1400
1300 1400

NameError: name 'pd' is not defined

In [48]:
df = pl.concat(dflist)

In [50]:
df

shape: (156_900, 4)
┌────────────────┬──────────┬────────────┬─────────────────────────────────┐
│ gene           ┆ breadth  ┆ metag      ┆ species                         │
│ ---            ┆ ---      ┆ ---        ┆ ---                             │
│ str            ┆ f64      ┆ str        ┆ str                             │
╞════════════════╪══════════╪════════════╪═════════════════════════════════╡
│ BCJOJFGP_00839 ┆ 0.998889 ┆ ERR8314788 ┆ s__Prevotella sp000434975       │
│ CHAJGCIB_01628 ┆ 1.0      ┆ ERR8314788 ┆ s__Prevotella sp000434975       │
│ PJFPEDHO_01064 ┆ 0.858641 ┆ ERR8314788 ┆ s__Prevotella sp000434975       │
│ ABGMHDFK_01758 ┆ 0.974052 ┆ ERR8314788 ┆ s__Prevotella sp000434975       │
│ LPDFMKHA_01513 ┆ 0.956522 ┆ ERR8314788 ┆ s__Prevotella sp000434975       │
│ …              ┆ …        ┆ …          ┆ …                               │
│ AKLOHKAG_01416 ┆ 0.193215 ┆ SRR8960391 ┆ s__Mogibacterium_A kristiansen… │
│ NADIOELI_00170 ┆ 0.0      ┆ SRR8960391 ┆ s__Mogibacterium_A kristiansen… │
│ IEPMJGAI_00771 ┆ 1.0      ┆ SRR8960391 ┆ s__Mogibacterium_A kristiansen… │
│ FMBBPIHC_01435 ┆ 0.742044 ┆ SRR8960391 ┆ s__Mogibacterium_A kristiansen… │
│ LJHBCGLM_01294 ┆ 0.0      ┆ SRR8960391 ┆ s__Mogibacterium_A kristiansen… │
└────────────────┴──────────┴────────────┴─────────────────────────────────┘

In [57]:
agg_df = df.group_by(['species', 'gene']).agg(
    ((pl.col("breadth") > 0.1).sum() / pl.col("breadth").len()).alias("f")
)
agg_df

shape: (1_569, 3)
┌─────────────────────────────┬────────────────┬──────┐
│ species                     ┆ gene           ┆ f    │
│ ---                         ┆ ---            ┆ ---  │
│ str                         ┆ str            ┆ f64  │
╞═════════════════════════════╪════════════════╪══════╡
│ s__Prevotella sp000434975   ┆ OPNPMHKL_01111 ┆ 0.82 │
│ s__Holdemanella porci       ┆ CAJDFOMO_00564 ┆ 0.74 │
│ s__UBA2868 sp004552595      ┆ HEOOOEGB_00722 ┆ 0.61 │
│ s__Sodaliphilus sp004557565 ┆ AOJPJKKJ_01881 ┆ 0.91 │
│ s__Gemmiger qucibialis      ┆ OMLAPDIE_01597 ┆ 0.27 │
│ …                           ┆ …              ┆ …    │
│ s__Prevotella sp000434975   ┆ FFDABIAA_00367 ┆ 0.7  │
│ s__Sodaliphilus sp004557565 ┆ JFIMJEBI_00808 ┆ 0.91 │
│ s__Prevotella sp000434975   ┆ LPDFMKHA_01233 ┆ 0.71 │
│ s__Prevotella sp002251295   ┆ JKBOFALP_01720 ┆ 0.67 │
│ s__Sodaliphilus sp004557565 ┆ LKFMHAMA_00022 ┆ 0.89 │
└─────────────────────────────┴────────────────┴──────┘

In [64]:
for species in agg_df['species'].unique():
    print(species)
    foo_df = agg_df.filter(pl.col("species") == species)
    print(foo_df.sort(by='f').filter(pl.col('f') > 0.8))

s__Bariatricus sp004560705
shape: (22, 3)
┌────────────────────────────┬────────────────┬──────┐
│ species                    ┆ gene           ┆ f    │
│ ---                        ┆ ---            ┆ ---  │
│ str                        ┆ str            ┆ f64  │
╞════════════════════════════╪════════════════╪══════╡
│ s__Bariatricus sp004560705 ┆ ELOEBFJM_01459 ┆ 0.81 │
│ s__Bariatricus sp004560705 ┆ KJMAJKMB_02318 ┆ 0.81 │
│ s__Bariatricus sp004560705 ┆ LNGHPPMH_01876 ┆ 0.81 │
│ s__Bariatricus sp004560705 ┆ EMNHIHKA_01693 ┆ 0.82 │
│ s__Bariatricus sp004560705 ┆ LNGHPPMH_00679 ┆ 0.83 │
│ …                          ┆ …              ┆ …    │
│ s__Bariatricus sp004560705 ┆ AIEIMHOC_00182 ┆ 0.89 │
│ s__Bariatricus sp004560705 ┆ FMMMFAAO_00746 ┆ 0.89 │
│ s__Bariatricus sp004560705 ┆ LEHFNBLN_02301 ┆ 0.93 │
│ s__Bariatricus sp004560705 ┆ LEHFNBLN_00701 ┆ 0.95 │
│ s__Bariatricus sp004560705 ┆ CHOLCMOC_00863 ┆ 0.97 │
└────────────────────────────┴────────────────┴──────┘
s__Mogibacterium_A kristiansenii
shape: (3, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Mogibacterium_A kristiansen… ┆ NGANNMPO_01097 ┆ 0.87 │
│ s__Mogibacterium_A kristiansen… ┆ AAOFCIJB_00277 ┆ 1.0  │
│ s__Mogibacterium_A kristiansen… ┆ JMKEGFFJ_01326 ┆ 1.0  │
└─────────────────────────────────┴────────────────┴──────┘
s__Roseburia inulinivorans
shape: (4, 3)
┌────────────────────────────┬────────────────┬──────┐
│ species                    ┆ gene           ┆ f    │
│ ---                        ┆ ---            ┆ ---  │
│ str                        ┆ str            ┆ f64  │
╞════════════════════════════╪════════════════╪══════╡
│ s__Roseburia inulinivorans ┆ HGAHBKMD_00273 ┆ 0.81 │
│ s__Roseburia inulinivorans ┆ HGAHBKMD_00261 ┆ 0.83 │
│ s__Roseburia inulinivorans ┆ HGAHBKMD_00299 ┆ 0.83 │
│ s__Roseburia inulinivorans ┆ HGAHBKMD_00300 ┆ 0.84 │
└────────────────────────────┴────────────────┴──────┘
s__UBA2868 sp004552595
shape: (6, 3)
┌────────────────────────┬────────────────┬──────┐
│ species                ┆ gene           ┆ f    │
│ ---                    ┆ ---            ┆ ---  │
│ str                    ┆ str            ┆ f64  │
╞════════════════════════╪════════════════╪══════╡
│ s__UBA2868 sp004552595 ┆ GLNAKBGL_01080 ┆ 0.81 │
│ s__UBA2868 sp004552595 ┆ IPIMNMMB_00240 ┆ 0.83 │
│ s__UBA2868 sp004552595 ┆ IEHIAHIF_00466 ┆ 0.84 │
│ s__UBA2868 sp004552595 ┆ JGIIMPIP_01734 ┆ 0.84 │
│ s__UBA2868 sp004552595 ┆ KMEHCMKH_00746 ┆ 0.9  │
│ s__UBA2868 sp004552595 ┆ GHILBDOG_00591 ┆ 0.97 │
└────────────────────────┴────────────────┴──────┘
s__Sodaliphilus sp004557565
shape: (523, 3)
┌─────────────────────────────┬────────────────┬──────┐
│ species                     ┆ gene           ┆ f    │
│ ---                         ┆ ---            ┆ ---  │
│ str                         ┆ str            ┆ f64  │
╞═════════════════════════════╪════════════════╪══════╡
│ s__Sodaliphilus sp004557565 ┆ FFPKJLEH_01889 ┆ 0.81 │
│ s__Sodaliphilus sp004557565 ┆ AMGICADG_01128 ┆ 0.81 │
│ s__Sodaliphilus sp004557565 ┆ GFGDBLKC_02104 ┆ 0.81 │
│ s__Sodaliphilus sp004557565 ┆ LFLAOHMB_01227 ┆ 0.81 │
│ s__Sodaliphilus sp004557565 ┆ FCPBIAPK_02111 ┆ 0.81 │
│ …                           ┆ …              ┆ …    │
│ s__Sodaliphilus sp004557565 ┆ JJHEGIOA_01813 ┆ 0.96 │
│ s__Sodaliphilus sp004557565 ┆ HENFICJG_01772 ┆ 0.96 │
│ s__Sodaliphilus sp004557565 ┆ DPOAHOKO_01468 ┆ 0.96 │
│ s__Sodaliphilus sp004557565 ┆ MPEKMBOO_01380 ┆ 0.96 │
│ s__Sodaliphilus sp004557565 ┆ JHPFMEME_00905 ┆ 0.98 │
└─────────────────────────────┴────────────────┴──────┘
s__JALFVM01 sp022787145
shape: (1, 3)
┌─────────────────────────┬────────────────┬──────┐
│ species                 ┆ gene           ┆ f    │
│ ---                     ┆ ---            ┆ ---  │
│ str                     ┆ str            ┆ f64  │
╞═════════════════════════╪════════════════╪══════╡
│ s__JALFVM01 sp022787145 ┆ JDFEBBFI_00464 ┆ 0.81 │
└─────────────────────────┴────────────────┴──────┘
s__Phascolarctobacterium_A succinatutens
shape: (10, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Phascolarctobacterium_A suc… ┆ ACGCMIFI_00234 ┆ 0.81 │
│ s__Phascolarctobacterium_A suc… ┆ CNFNFEIB_01943 ┆ 0.82 │
│ s__Phascolarctobacterium_A suc… ┆ CNDPHPMH_00640 ┆ 0.84 │
│ s__Phascolarctobacterium_A suc… ┆ DHJLCIIK_01145 ┆ 0.84 │
│ s__Phascolarctobacterium_A suc… ┆ GGLHANJG_01414 ┆ 0.87 │
│ s__Phascolarctobacterium_A suc… ┆ LDBAILDD_01769 ┆ 0.9  │
│ s__Phascolarctobacterium_A suc… ┆ CNENGHLA_01260 ┆ 0.91 │
│ s__Phascolarctobacterium_A suc… ┆ IFIBFMPA_00800 ┆ 0.93 │
│ s__Phascolarctobacterium_A suc… ┆ EHOAPHDI_01174 ┆ 0.95 │
│ s__Phascolarctobacterium_A suc… ┆ CNENGHLA_00658 ┆ 0.96 │
└─────────────────────────────────┴────────────────┴──────┘
s__Cryptobacteroides sp900546925
shape: (130, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Cryptobacteroides sp9005469… ┆ GGBBOKIP_00385 ┆ 0.81 │
│ s__Cryptobacteroides sp9005469… ┆ FNIGJHLI_01255 ┆ 0.81 │
│ s__Cryptobacteroides sp9005469… ┆ DPAEODGL_01450 ┆ 0.81 │
│ s__Cryptobacteroides sp9005469… ┆ FNIGJHLI_00173 ┆ 0.81 │
│ s__Cryptobacteroides sp9005469… ┆ JEGHMLOF_01375 ┆ 0.81 │
│ …                               ┆ …              ┆ …    │
│ s__Cryptobacteroides sp9005469… ┆ BDFOMKKK_00335 ┆ 0.9  │
│ s__Cryptobacteroides sp9005469… ┆ BEKEPKDC_00417 ┆ 0.9  │
│ s__Cryptobacteroides sp9005469… ┆ NEEJCNGM_00839 ┆ 0.92 │
│ s__Cryptobacteroides sp9005469… ┆ CMHHCIHA_00622 ┆ 0.93 │
│ s__Cryptobacteroides sp9005469… ┆ FIKGMHDC_00998 ┆ 0.94 │
└─────────────────────────────────┴────────────────┴──────┘
s__Lactobacillus amylovorus
shape: (20, 3)
┌─────────────────────────────┬────────────────┬──────┐
│ species                     ┆ gene           ┆ f    │
│ ---                         ┆ ---            ┆ ---  │
│ str                         ┆ str            ┆ f64  │
╞═════════════════════════════╪════════════════╪══════╡
│ s__Lactobacillus amylovorus ┆ NKKPHFMM_01729 ┆ 0.81 │
│ s__Lactobacillus amylovorus ┆ IAOGNCPA_00195 ┆ 0.81 │
│ s__Lactobacillus amylovorus ┆ GEDODALP_01206 ┆ 0.81 │
│ s__Lactobacillus amylovorus ┆ CPKOPDLF_00550 ┆ 0.82 │
│ s__Lactobacillus amylovorus ┆ LEAIKLIG_01457 ┆ 0.82 │
│ …                           ┆ …              ┆ …    │
│ s__Lactobacillus amylovorus ┆ OBGMJDLM_01221 ┆ 0.88 │
│ s__Lactobacillus amylovorus ┆ OMBJBIHD_01711 ┆ 0.88 │
│ s__Lactobacillus amylovorus ┆ HPBCBKPJ_01887 ┆ 0.89 │
│ s__Lactobacillus amylovorus ┆ BBOFCOCJ_01349 ┆ 0.91 │
│ s__Lactobacillus amylovorus ┆ CPLGDGDL_01434 ┆ 0.92 │
└─────────────────────────────┴────────────────┴──────┘
s__Fimisoma sp002320005
shape: (1, 3)
┌─────────────────────────┬────────────────┬──────┐
│ species                 ┆ gene           ┆ f    │
│ ---                     ┆ ---            ┆ ---  │
│ str                     ┆ str            ┆ f64  │
╞═════════════════════════╪════════════════╪══════╡
│ s__Fimisoma sp002320005 ┆ JAOEKFJL_01590 ┆ 0.92 │
└─────────────────────────┴────────────────┴──────┘
s__Prevotella sp002251295
shape: (90, 3)
┌───────────────────────────┬────────────────┬──────┐
│ species                   ┆ gene           ┆ f    │
│ ---                       ┆ ---            ┆ ---  │
│ str                       ┆ str            ┆ f64  │
╞═══════════════════════════╪════════════════╪══════╡
│ s__Prevotella sp002251295 ┆ JEGLOHPD_00328 ┆ 0.81 │
│ s__Prevotella sp002251295 ┆ EFBIIPPC_01725 ┆ 0.81 │
│ s__Prevotella sp002251295 ┆ OEDAEGJB_01922 ┆ 0.81 │
│ s__Prevotella sp002251295 ┆ JEGLOHPD_01748 ┆ 0.81 │
│ s__Prevotella sp002251295 ┆ OAHOCONN_01297 ┆ 0.81 │
│ …                         ┆ …              ┆ …    │
│ s__Prevotella sp002251295 ┆ KPACIEHJ_00390 ┆ 0.91 │
│ s__Prevotella sp002251295 ┆ KINAFDOL_01550 ┆ 0.92 │
│ s__Prevotella sp002251295 ┆ IPDEFMND_01992 ┆ 0.93 │
│ s__Prevotella sp002251295 ┆ MBJGDHEG_00059 ┆ 0.93 │
│ s__Prevotella sp002251295 ┆ COCKKAPE_02026 ┆ 0.93 │
└───────────────────────────┴────────────────┴──────┘
s__Gemmiger qucibialis
shape: (10, 3)
┌────────────────────────┬────────────────┬──────┐
│ species                ┆ gene           ┆ f    │
│ ---                    ┆ ---            ┆ ---  │
│ str                    ┆ str            ┆ f64  │
╞════════════════════════╪════════════════╪══════╡
│ s__Gemmiger qucibialis ┆ PEAPMGON_00222 ┆ 0.81 │
│ s__Gemmiger qucibialis ┆ EBFKGAGP_00060 ┆ 0.82 │
│ s__Gemmiger qucibialis ┆ DLCICKOP_02020 ┆ 0.84 │
│ s__Gemmiger qucibialis ┆ GOPMMJLD_01454 ┆ 0.85 │
│ s__Gemmiger qucibialis ┆ AGHFCGHF_02266 ┆ 0.89 │
│ s__Gemmiger qucibialis ┆ LAOGNEID_00570 ┆ 0.9  │
│ s__Gemmiger qucibialis ┆ IPGJNJJC_00242 ┆ 0.9  │
│ s__Gemmiger qucibialis ┆ CLHLFGFN_00542 ┆ 0.91 │
│ s__Gemmiger qucibialis ┆ EANOHOOJ_01559 ┆ 0.92 │
│ s__Gemmiger qucibialis ┆ GLIPJGEI_00065 ┆ 0.94 │
└────────────────────────┴────────────────┴──────┘
s__Holdemanella porci
shape: (0, 3)
┌─────────┬──────┬─────┐
│ species ┆ gene ┆ f   │
│ ---     ┆ ---  ┆ --- │
│ str     ┆ str  ┆ f64 │
╞═════════╪══════╪═════╡
└─────────┴──────┴─────┘
s__Prevotella sp000434975
shape: (82, 3)
┌───────────────────────────┬────────────────┬──────┐
│ species                   ┆ gene           ┆ f    │
│ ---                       ┆ ---            ┆ ---  │
│ str                       ┆ str            ┆ f64  │
╞═══════════════════════════╪════════════════╪══════╡
│ s__Prevotella sp000434975 ┆ COIBJELC_00608 ┆ 0.81 │
│ s__Prevotella sp000434975 ┆ CHAJGCIB_01628 ┆ 0.81 │
│ s__Prevotella sp000434975 ┆ ANNBMKBB_01069 ┆ 0.81 │
│ s__Prevotella sp000434975 ┆ DKNPLDGH_00708 ┆ 0.81 │
│ s__Prevotella sp000434975 ┆ ABGMHDFK_00248 ┆ 0.81 │
│ …                         ┆ …              ┆ …    │
│ s__Prevotella sp000434975 ┆ MLIECJNI_00172 ┆ 0.92 │
│ s__Prevotella sp000434975 ┆ PDHLFJAL_00903 ┆ 0.92 │
│ s__Prevotella sp000434975 ┆ HGGBKJHA_00064 ┆ 0.92 │
│ s__Prevotella sp000434975 ┆ BAIAEPON_01639 ┆ 0.92 │
│ s__Prevotella sp000434975 ┆ AJCJGFNH_00477 ┆ 0.93 │
└───────────────────────────┴────────────────┴──────┘

In [70]:
df.filter((pl.col("gene") == 'EHOAPHDI_01174')).sort(by='breadth')

shape: (100, 4)
┌────────────────┬─────────┬─────────────┬─────────────────────────────────┐
│ gene           ┆ breadth ┆ metag       ┆ species                         │
│ ---            ┆ ---     ┆ ---         ┆ ---                             │
│ str            ┆ f64     ┆ str         ┆ str                             │
╞════════════════╪═════════╪═════════════╪═════════════════════════════════╡
│ EHOAPHDI_01174 ┆ 0.0     ┆ SRR12795775 ┆ s__Phascolarctobacterium_A suc… │
│ EHOAPHDI_01174 ┆ 0.0     ┆ SRR8655118  ┆ s__Phascolarctobacterium_A suc… │
│ EHOAPHDI_01174 ┆ 0.0     ┆ ERR3212024  ┆ s__Phascolarctobacterium_A suc… │
│ EHOAPHDI_01174 ┆ 0.0     ┆ SRR5240729  ┆ s__Phascolarctobacterium_A suc… │
│ EHOAPHDI_01174 ┆ 0.0     ┆ SRR12795790 ┆ s__Phascolarctobacterium_A suc… │
│ …              ┆ …       ┆ …           ┆ …                               │
│ EHOAPHDI_01174 ┆ 1.0     ┆ ERR1135331  ┆ s__Phascolarctobacterium_A suc… │
│ EHOAPHDI_01174 ┆ 1.0     ┆ SRR11124923 ┆ s__Phascolarctobacterium_A suc… │
│ EHOAPHDI_01174 ┆ 1.0     ┆ SRR11489769 ┆ s__Phascolarctobacterium_A suc… │
│ EHOAPHDI_01174 ┆ 1.0     ┆ SRR10209667 ┆ s__Phascolarctobacterium_A suc… │
│ EHOAPHDI_01174 ┆ 1.0     ┆ ERR1135238  ┆ s__Phascolarctobacterium_A suc… │
└────────────────┴─────────┴─────────────┴─────────────────────────────────┘

In [71]:
df.filter((pl.col("gene") == 'EHOAPHDI_01174')).sort(by='breadth').filter(pl.col("metag") == "ERR1135199")

shape: (1, 4)
┌────────────────┬──────────┬────────────┬─────────────────────────────────┐
│ gene           ┆ breadth  ┆ metag      ┆ species                         │
│ ---            ┆ ---      ┆ ---        ┆ ---                             │
│ str            ┆ f64      ┆ str        ┆ str                             │
╞════════════════╪══════════╪════════════╪═════════════════════════════════╡
│ EHOAPHDI_01174 ┆ 0.279642 ┆ ERR1135199 ┆ s__Phascolarctobacterium_A suc… │
└────────────────┴──────────┴────────────┴─────────────────────────────────┘