# Look at mapping breadth and depth of 100 x metagenomes to singleclust genes

In [10]:
import polars as pl
import glob
import os

## Read in individual metag x species singleclust depth reports

These files contain depth-of-mapping information for all our genes.

In [11]:
DIR='../outputs.cds/singleclust/bam.bak'
template = '../outputs.cds/singleclust/bam/{metag}.x.{species}.depth.txt'

def read_depth(metag, species):
    filename = template.format(metag=metag, species=species)
    df = pl.read_csv(filename, separator='\t', has_header=False,
                 new_columns=('gene', 'pos', 'cov', 'foo'))
    sum_df = df.group_by('gene').agg(
        ((pl.col("cov") > 0).sum() / pl.col("pos").len()).alias("breadth")
    ).with_columns(
        (pl.lit(metag).alias("metag")),
        (pl.lit(species).alias("species"))
)
    return sum_df

read_depth('ERR1135199', 's__Cryptobacteroides sp900546925')

shape: (248, 4)
┌────────────────┬──────────┬────────────┬─────────────────────────────────┐
│ gene           ┆ breadth  ┆ metag      ┆ species                         │
│ ---            ┆ ---      ┆ ---        ┆ ---                             │
│ str            ┆ f64      ┆ str        ┆ str                             │
╞════════════════╪══════════╪════════════╪═════════════════════════════════╡
│ BEKEPKDC_01498 ┆ 0.795533 ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ OIJDNDLK_01266 ┆ 0.64176  ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ CPBNAKKL_00778 ┆ 0.618519 ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ BEKEPKDC_01359 ┆ 0.706751 ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ EPLMDCHM_00231 ┆ 0.760417 ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ …              ┆ …        ┆ …          ┆ …                               │
│ ILFIENBF_01329 ┆ 0.262055 ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ KJEHENCE_00427 ┆ 0.14128  ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ OIJDNDLK_00513 ┆ 0.389653 ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ BNDPAENK_02662 ┆ 0.940568 ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
│ MFHJPMDA_00446 ┆ 0.96063  ┆ ERR1135199 ┆ s__Cryptobacteroides sp9005469… │
└────────────────┴──────────┴────────────┴─────────────────────────────────┘

In [12]:
# Read them all in!
filenames = glob.glob(f"{DIR}/*.depth.txt")

dflist = []
for i, n in enumerate(filenames):
    if i % 100 == 0:
        print(f"{i} of {len(filenames)}")
    n = os.path.basename(n)
    metag, _, species, _ = n.split('.', 3)
    dflist.append(read_depth(metag, species))

depth_df = pl.concat(dflist)

print(f"read {len(filenames)} depth files.")

0 of 1400
100 of 1400
200 of 1400
300 of 1400
400 of 1400
500 of 1400
600 of 1400
700 of 1400
800 of 1400
900 of 1400
1000 of 1400
1100 of 1400
1200 of 1400
1300 of 1400
read 1400 depth files.

In [13]:
depth_df

shape: (144_900, 4)
┌────────────────┬──────────┬─────────────┬────────────────────────────┐
│ gene           ┆ breadth  ┆ metag       ┆ species                    │
│ ---            ┆ ---      ┆ ---         ┆ ---                        │
│ str            ┆ f64      ┆ str         ┆ str                        │
╞════════════════╪══════════╪═════════════╪════════════════════════════╡
│ GHILBDOG_00591 ┆ 0.78905  ┆ ERR8314733  ┆ s__UBA2868 sp004552595     │
│ NBDIFHPL_00838 ┆ 0.657193 ┆ ERR8314733  ┆ s__UBA2868 sp004552595     │
│ MDNFKAHM_01289 ┆ 0.582289 ┆ ERR8314733  ┆ s__UBA2868 sp004552595     │
│ EEPGLDGH_01407 ┆ 0.823642 ┆ ERR8314733  ┆ s__UBA2868 sp004552595     │
│ CPAKOFGF_01213 ┆ 0.917526 ┆ ERR8314733  ┆ s__UBA2868 sp004552595     │
│ …              ┆ …        ┆ …           ┆ …                          │
│ PAFBNDJL_01579 ┆ 0.0      ┆ SRR12795793 ┆ s__Bariatricus sp004560705 │
│ EMNHIHKA_01693 ┆ 0.705185 ┆ SRR12795793 ┆ s__Bariatricus sp004560705 │
│ OOABBEGM_02263 ┆ 0.882353 ┆ SRR12795793 ┆ s__Bariatricus sp004560705 │
│ NDCIOGGG_00214 ┆ 0.521484 ┆ SRR12795793 ┆ s__Bariatricus sp004560705 │
│ ELOEBFJM_01459 ┆ 0.571654 ┆ SRR12795793 ┆ s__Bariatricus sp004560705 │
└────────────────┴──────────┴─────────────┴────────────────────────────┘

## Summarize our mapping depth results across all the metagenomes

In [14]:
# require 10% of each gene to be covered by at least one read
BREADTH_CUTOFF = 0.1

In [15]:
# aggregate across all metagenomes;
# calculate fraction of metagenomes for which gene mapping exceeds our breadth cutoff
agg_df = depth_df.group_by(['species', 'gene']).agg(
    ((pl.col("breadth") >= BREADTH_CUTOFF).sum() / pl.col("breadth").len()).alias("f")
)
agg_df

shape: (1_449, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Prevotella sp000434975       ┆ EEMFJJMB_01353 ┆ 0.83 │
│ s__Prevotella sp000434975       ┆ PMHDHLGK_00812 ┆ 0.43 │
│ s__Sodaliphilus sp004557565     ┆ MMKFDMID_01280 ┆ 0.9  │
│ s__Cryptobacteroides sp9005469… ┆ CPBNAKKL_01491 ┆ 0.83 │
│ s__Sodaliphilus sp004557565     ┆ CNKENCMK_01602 ┆ 0.87 │
│ …                               ┆ …              ┆ …    │
│ s__Gemmiger qucibialis          ┆ KDIJJGOD_01445 ┆ 0.21 │
│ s__Cryptobacteroides sp9005469… ┆ LELOEEPG_00778 ┆ 0.8  │
│ s__UBA2868 sp004552595          ┆ PCFNEHJA_00919 ┆ 0.62 │
│ s__Cryptobacteroides sp9005469… ┆ HMMHNFMB_01135 ┆ 0.78 │
│ s__Sodaliphilus sp004557565     ┆ ALALOGAM_01006 ┆ 0.87 │
└─────────────────────────────────┴────────────────┴──────┘

In [16]:
# print information out by species
for species in sorted(agg_df['species'].unique()):
    print(species)
    foo_df = agg_df.filter(pl.col("species") == species)
    print(foo_df.sort(by='f').filter(pl.col('f') > 0.8))

s__Bariatricus sp004560705
shape: (15, 3)
┌────────────────────────────┬────────────────┬──────┐
│ species                    ┆ gene           ┆ f    │
│ ---                        ┆ ---            ┆ ---  │
│ str                        ┆ str            ┆ f64  │
╞════════════════════════════╪════════════════╪══════╡
│ s__Bariatricus sp004560705 ┆ ELOEBFJM_01459 ┆ 0.81 │
│ s__Bariatricus sp004560705 ┆ EMNHIHKA_01693 ┆ 0.82 │
│ s__Bariatricus sp004560705 ┆ LNGHPPMH_00679 ┆ 0.83 │
│ s__Bariatricus sp004560705 ┆ NOACAEKI_00860 ┆ 0.83 │
│ s__Bariatricus sp004560705 ┆ OOABBEGM_02263 ┆ 0.84 │
│ …                          ┆ …              ┆ …    │
│ s__Bariatricus sp004560705 ┆ NDCIOGGG_00214 ┆ 0.89 │
│ s__Bariatricus sp004560705 ┆ AIEIMHOC_00182 ┆ 0.89 │
│ s__Bariatricus sp004560705 ┆ LEHFNBLN_02301 ┆ 0.93 │
│ s__Bariatricus sp004560705 ┆ LEHFNBLN_00701 ┆ 0.95 │
│ s__Bariatricus sp004560705 ┆ CHOLCMOC_00863 ┆ 0.97 │
└────────────────────────────┴────────────────┴──────┘
s__Cryptobacteroides sp900546925
shape: (125, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Cryptobacteroides sp9005469… ┆ IKEOPBPE_00959 ┆ 0.81 │
│ s__Cryptobacteroides sp9005469… ┆ LELOEEPG_01706 ┆ 0.81 │
│ s__Cryptobacteroides sp9005469… ┆ LELOEEPG_00745 ┆ 0.81 │
│ s__Cryptobacteroides sp9005469… ┆ FNIGJHLI_00173 ┆ 0.81 │
│ s__Cryptobacteroides sp9005469… ┆ OIJDNDLK_01211 ┆ 0.81 │
│ …                               ┆ …              ┆ …    │
│ s__Cryptobacteroides sp9005469… ┆ HGGDIOJJ_00346 ┆ 0.89 │
│ s__Cryptobacteroides sp9005469… ┆ BDFOMKKK_00335 ┆ 0.9  │
│ s__Cryptobacteroides sp9005469… ┆ BEKEPKDC_00417 ┆ 0.9  │
│ s__Cryptobacteroides sp9005469… ┆ CMHHCIHA_00622 ┆ 0.93 │
│ s__Cryptobacteroides sp9005469… ┆ FIKGMHDC_00998 ┆ 0.94 │
└─────────────────────────────────┴────────────────┴──────┘
s__Fimisoma sp002320005
shape: (1, 3)
┌─────────────────────────┬────────────────┬──────┐
│ species                 ┆ gene           ┆ f    │
│ ---                     ┆ ---            ┆ ---  │
│ str                     ┆ str            ┆ f64  │
╞═════════════════════════╪════════════════╪══════╡
│ s__Fimisoma sp002320005 ┆ JAOEKFJL_01590 ┆ 0.92 │
└─────────────────────────┴────────────────┴──────┘
s__Gemmiger qucibialis
shape: (10, 3)
┌────────────────────────┬────────────────┬──────┐
│ species                ┆ gene           ┆ f    │
│ ---                    ┆ ---            ┆ ---  │
│ str                    ┆ str            ┆ f64  │
╞════════════════════════╪════════════════╪══════╡
│ s__Gemmiger qucibialis ┆ PEAPMGON_00222 ┆ 0.81 │
│ s__Gemmiger qucibialis ┆ EBFKGAGP_00060 ┆ 0.82 │
│ s__Gemmiger qucibialis ┆ DLCICKOP_02020 ┆ 0.84 │
│ s__Gemmiger qucibialis ┆ GOPMMJLD_01454 ┆ 0.85 │
│ s__Gemmiger qucibialis ┆ AGHFCGHF_02266 ┆ 0.89 │
│ s__Gemmiger qucibialis ┆ LAOGNEID_00570 ┆ 0.9  │
│ s__Gemmiger qucibialis ┆ IPGJNJJC_00242 ┆ 0.9  │
│ s__Gemmiger qucibialis ┆ CLHLFGFN_00542 ┆ 0.91 │
│ s__Gemmiger qucibialis ┆ EANOHOOJ_01559 ┆ 0.92 │
│ s__Gemmiger qucibialis ┆ GLIPJGEI_00065 ┆ 0.94 │
└────────────────────────┴────────────────┴──────┘
s__Holdemanella porci
shape: (0, 3)
┌─────────┬──────┬─────┐
│ species ┆ gene ┆ f   │
│ ---     ┆ ---  ┆ --- │
│ str     ┆ str  ┆ f64 │
╞═════════╪══════╪═════╡
└─────────┴──────┴─────┘
s__JALFVM01 sp022787145
shape: (1, 3)
┌─────────────────────────┬────────────────┬──────┐
│ species                 ┆ gene           ┆ f    │
│ ---                     ┆ ---            ┆ ---  │
│ str                     ┆ str            ┆ f64  │
╞═════════════════════════╪════════════════╪══════╡
│ s__JALFVM01 sp022787145 ┆ JDFEBBFI_00464 ┆ 0.81 │
└─────────────────────────┴────────────────┴──────┘
s__Lactobacillus amylovorus
shape: (18, 3)
┌─────────────────────────────┬────────────────┬──────┐
│ species                     ┆ gene           ┆ f    │
│ ---                         ┆ ---            ┆ ---  │
│ str                         ┆ str            ┆ f64  │
╞═════════════════════════════╪════════════════╪══════╡
│ s__Lactobacillus amylovorus ┆ NKKPHFMM_01729 ┆ 0.81 │
│ s__Lactobacillus amylovorus ┆ IAOGNCPA_00195 ┆ 0.81 │
│ s__Lactobacillus amylovorus ┆ JOFDALNO_00602 ┆ 0.82 │
│ s__Lactobacillus amylovorus ┆ LEAIKLIG_01457 ┆ 0.82 │
│ s__Lactobacillus amylovorus ┆ CPKOPDLF_00550 ┆ 0.82 │
│ …                           ┆ …              ┆ …    │
│ s__Lactobacillus amylovorus ┆ OBGMJDLM_01221 ┆ 0.88 │
│ s__Lactobacillus amylovorus ┆ OMBJBIHD_01711 ┆ 0.88 │
│ s__Lactobacillus amylovorus ┆ HPBCBKPJ_01887 ┆ 0.89 │
│ s__Lactobacillus amylovorus ┆ BBOFCOCJ_01349 ┆ 0.91 │
│ s__Lactobacillus amylovorus ┆ CPLGDGDL_01434 ┆ 0.92 │
└─────────────────────────────┴────────────────┴──────┘
s__Mogibacterium_A kristiansenii
shape: (3, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Mogibacterium_A kristiansen… ┆ NGANNMPO_01097 ┆ 0.87 │
│ s__Mogibacterium_A kristiansen… ┆ AAOFCIJB_00277 ┆ 1.0  │
│ s__Mogibacterium_A kristiansen… ┆ JMKEGFFJ_01326 ┆ 1.0  │
└─────────────────────────────────┴────────────────┴──────┘
s__Phascolarctobacterium_A succinatutens
shape: (5, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Phascolarctobacterium_A suc… ┆ DHJLCIIK_01145 ┆ 0.84 │
│ s__Phascolarctobacterium_A suc… ┆ GGLHANJG_01414 ┆ 0.87 │
│ s__Phascolarctobacterium_A suc… ┆ LDBAILDD_01769 ┆ 0.9  │
│ s__Phascolarctobacterium_A suc… ┆ CNENGHLA_01260 ┆ 0.91 │
│ s__Phascolarctobacterium_A suc… ┆ CNENGHLA_00658 ┆ 0.96 │
└─────────────────────────────────┴────────────────┴──────┘
s__Prevotella sp000434975
shape: (78, 3)
┌───────────────────────────┬────────────────┬──────┐
│ species                   ┆ gene           ┆ f    │
│ ---                       ┆ ---            ┆ ---  │
│ str                       ┆ str            ┆ f64  │
╞═══════════════════════════╪════════════════╪══════╡
│ s__Prevotella sp000434975 ┆ IBGIKLDL_02009 ┆ 0.81 │
│ s__Prevotella sp000434975 ┆ IBOOIAKE_00716 ┆ 0.81 │
│ s__Prevotella sp000434975 ┆ DEENMOAI_01503 ┆ 0.81 │
│ s__Prevotella sp000434975 ┆ JDKJHEGC_01287 ┆ 0.81 │
│ s__Prevotella sp000434975 ┆ BDOBMDOL_01085 ┆ 0.81 │
│ …                         ┆ …              ┆ …    │
│ s__Prevotella sp000434975 ┆ BAIAEPON_01639 ┆ 0.92 │
│ s__Prevotella sp000434975 ┆ PDHLFJAL_00903 ┆ 0.92 │
│ s__Prevotella sp000434975 ┆ MLIECJNI_00172 ┆ 0.92 │
│ s__Prevotella sp000434975 ┆ HGGBKJHA_00064 ┆ 0.92 │
│ s__Prevotella sp000434975 ┆ AJCJGFNH_00477 ┆ 0.93 │
└───────────────────────────┴────────────────┴──────┘
s__Prevotella sp002251295
shape: (81, 3)
┌───────────────────────────┬────────────────┬──────┐
│ species                   ┆ gene           ┆ f    │
│ ---                       ┆ ---            ┆ ---  │
│ str                       ┆ str            ┆ f64  │
╞═══════════════════════════╪════════════════╪══════╡
│ s__Prevotella sp002251295 ┆ OAHOCONN_01297 ┆ 0.81 │
│ s__Prevotella sp002251295 ┆ OEDAEGJB_01922 ┆ 0.81 │
│ s__Prevotella sp002251295 ┆ JEGLOHPD_01748 ┆ 0.81 │
│ s__Prevotella sp002251295 ┆ GDBLKLPM_01100 ┆ 0.82 │
│ s__Prevotella sp002251295 ┆ KINAFDOL_01884 ┆ 0.82 │
│ …                         ┆ …              ┆ …    │
│ s__Prevotella sp002251295 ┆ KPACIEHJ_00390 ┆ 0.91 │
│ s__Prevotella sp002251295 ┆ GFALEAHI_01277 ┆ 0.91 │
│ s__Prevotella sp002251295 ┆ KINAFDOL_01550 ┆ 0.92 │
│ s__Prevotella sp002251295 ┆ IPDEFMND_01992 ┆ 0.93 │
│ s__Prevotella sp002251295 ┆ COCKKAPE_02026 ┆ 0.93 │
└───────────────────────────┴────────────────┴──────┘
s__Roseburia inulinivorans
shape: (4, 3)
┌────────────────────────────┬────────────────┬──────┐
│ species                    ┆ gene           ┆ f    │
│ ---                        ┆ ---            ┆ ---  │
│ str                        ┆ str            ┆ f64  │
╞════════════════════════════╪════════════════╪══════╡
│ s__Roseburia inulinivorans ┆ HGAHBKMD_00273 ┆ 0.81 │
│ s__Roseburia inulinivorans ┆ HGAHBKMD_00261 ┆ 0.83 │
│ s__Roseburia inulinivorans ┆ HGAHBKMD_00299 ┆ 0.83 │
│ s__Roseburia inulinivorans ┆ HGAHBKMD_00300 ┆ 0.84 │
└────────────────────────────┴────────────────┴──────┘
s__Sodaliphilus sp004557565
shape: (501, 3)
┌─────────────────────────────┬────────────────┬──────┐
│ species                     ┆ gene           ┆ f    │
│ ---                         ┆ ---            ┆ ---  │
│ str                         ┆ str            ┆ f64  │
╞═════════════════════════════╪════════════════╪══════╡
│ s__Sodaliphilus sp004557565 ┆ DDMOEMBK_01105 ┆ 0.81 │
│ s__Sodaliphilus sp004557565 ┆ GEGNICLP_00271 ┆ 0.81 │
│ s__Sodaliphilus sp004557565 ┆ IKJKFBBO_00189 ┆ 0.81 │
│ s__Sodaliphilus sp004557565 ┆ LFLAOHMB_01227 ┆ 0.81 │
│ s__Sodaliphilus sp004557565 ┆ GFGDBLKC_02104 ┆ 0.81 │
│ …                           ┆ …              ┆ …    │
│ s__Sodaliphilus sp004557565 ┆ JJHEGIOA_01813 ┆ 0.96 │
│ s__Sodaliphilus sp004557565 ┆ MPEKMBOO_01380 ┆ 0.96 │
│ s__Sodaliphilus sp004557565 ┆ COJGPLPN_01769 ┆ 0.96 │
│ s__Sodaliphilus sp004557565 ┆ HENFICJG_01772 ┆ 0.96 │
│ s__Sodaliphilus sp004557565 ┆ JHPFMEME_00905 ┆ 0.98 │
└─────────────────────────────┴────────────────┴──────┘
s__UBA2868 sp004552595
shape: (6, 3)
┌────────────────────────┬────────────────┬──────┐
│ species                ┆ gene           ┆ f    │
│ ---                    ┆ ---            ┆ ---  │
│ str                    ┆ str            ┆ f64  │
╞════════════════════════╪════════════════╪══════╡
│ s__UBA2868 sp004552595 ┆ GLNAKBGL_01080 ┆ 0.81 │
│ s__UBA2868 sp004552595 ┆ IPIMNMMB_00240 ┆ 0.83 │
│ s__UBA2868 sp004552595 ┆ JGIIMPIP_01734 ┆ 0.84 │
│ s__UBA2868 sp004552595 ┆ IEHIAHIF_00466 ┆ 0.84 │
│ s__UBA2868 sp004552595 ┆ KMEHCMKH_00746 ┆ 0.9  │
│ s__UBA2868 sp004552595 ┆ GHILBDOG_00591 ┆ 0.97 │
└────────────────────────┴────────────────┴──────┘

## Explore specific gene/species/metag combinations

In [17]:
depth_df.filter((pl.col("gene") == 'EHOAPHDI_01174')).sort(by='breadth')

shape: (0, 4)
┌──────┬─────────┬───────┬─────────┐
│ gene ┆ breadth ┆ metag ┆ species │
│ ---  ┆ ---     ┆ ---   ┆ ---     │
│ str  ┆ f64     ┆ str   ┆ str     │
╞══════╪═════════╪═══════╪═════════╡
└──────┴─────────┴───────┴─────────┘

In [18]:
depth_df.filter((pl.col("gene") == 'EHOAPHDI_01174')).sort(by='breadth').filter(pl.col("metag") == "ERR1135199")

shape: (0, 4)
┌──────┬─────────┬───────┬─────────┐
│ gene ┆ breadth ┆ metag ┆ species │
│ ---  ┆ ---     ┆ ---   ┆ ---     │
│ str  ┆ f64     ┆ str   ┆ str     │
╞══════╪═════════╪═══════╪═════════╡
└──────┴─────────┴───────┴─────────┘