# Look at mapping breadth and depth of 100 x metagenomes to singleclust genes

In [1]:
import polars as pl
import glob
import os
import screed
import csv
import screed

## Read in individual metag x species singleclust depth reports

These files contain depth-of-mapping information for all our genes.

In [2]:
DIR='../outputs.cds/singleclust/bam'
template = '../outputs.cds/singleclust/bam/{metag}.x.{species}.depth.txt'

def read_depth_txt(metag, species, *, exclude_ends=75):
    filename = template.format(metag=metag, species=species)
    df = pl.read_csv(filename, separator='\t', has_header=False,
                 new_columns=('gene', 'pos', 'cov', 'foo')).select(['gene', 'pos', 'cov'])

    sum_df = df.group_by('gene').all().with_columns(
        # select slice [75:-75]
        (pl.col("pos").list.slice(exclude_ends, -exclude_ends).list.len()).alias("len"),
        (pl.col("cov").list.slice(exclude_ends, -exclude_ends)),
        (pl.col("cov").list.slice(exclude_ends, -exclude_ends).list.filter(pl.element() > 0)).list.len().alias("hits"),
    ).with_columns(
        (pl.lit(metag).alias("metag")),
        (pl.lit(species).alias("species")),
        # summarize: average depth across contig,
        (pl.col("cov").list.sum() / pl.col("len")).alias("depth_all"),
        # average depth across covered bases,
        (pl.col("cov").list.sum() / pl.col("hits")).alias("depth_cov"),
        # fraction of bases covered
        (pl.col("hits") / pl.col("cov").list.len()).alias("breadth"),
    ).select(["metag", "species", "gene", "len", "hits", "breadth", "depth_all", "depth_cov"])
    return sum_df

read_depth_txt('ERR1135199', 's__Cryptobacteroides sp900546925')

shape: (248, 8)
┌────────────┬───────────────────┬────────────────┬──────┬──────┬──────────┬───────────┬───────────┐
│ metag      ┆ species           ┆ gene           ┆ len  ┆ hits ┆ breadth  ┆ depth_all ┆ depth_cov │
│ ---        ┆ ---               ┆ ---            ┆ ---  ┆ ---  ┆ ---      ┆ ---       ┆ ---       │
│ str        ┆ str               ┆ str            ┆ u32  ┆ u32  ┆ f64      ┆ f64       ┆ f64       │
╞════════════╪═══════════════════╪════════════════╪══════╪══════╪══════════╪═══════════╪═══════════╡
│ ERR1135199 ┆ s__Cryptobacteroi ┆ HLFEEHJE_00326 ┆ 1059 ┆ 934  ┆ 0.881964 ┆ 1.807365  ┆ 2.049251  │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ JPFIBGDK_00461 ┆ 4623 ┆ 2261 ┆ 0.489076 ┆ 0.684404  ┆ 1.399381  │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ FNIGJHLI_01544 ┆ 423  ┆ 193  ┆ 0.456265 ┆ 0.650118  ┆ 1.42487   │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ JPFIBGDK_01534 ┆ 681  ┆ 0    ┆ 0.0      ┆ 0.0       ┆ NaN       │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ EPLMDCHM_00231 ┆ 2037 ┆ 1536 ┆ 0.75405  ┆ 1.232204  ┆ 1.634115  │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ …          ┆ …                 ┆ …              ┆ …    ┆ …    ┆ …        ┆ …         ┆ …         │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ BEKEPKDC_00812 ┆ 948  ┆ 500  ┆ 0.527426 ┆ 0.733122  ┆ 1.39      │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ CMHHCIHA_00622 ┆ 1185 ┆ 1012 ┆ 0.854008 ┆ 4.637975  ┆ 5.43083   │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ FNIGJHLI_02652 ┆ 1374 ┆ 1165 ┆ 0.847889 ┆ 1.47016   ┆ 1.733906  │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ FFGMIBGD_00294 ┆ 2691 ┆ 1400 ┆ 0.520253 ┆ 0.810479  ┆ 1.557857  │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
│ ERR1135199 ┆ s__Cryptobacteroi ┆ OIJDNDLK_00702 ┆ 1074 ┆ 0    ┆ 0.0      ┆ 0.0       ┆ NaN       │
│            ┆ des sp9005469…    ┆                ┆      ┆      ┆          ┆           ┆           │
└────────────┴───────────────────┴────────────────┴──────┴──────┴──────────┴───────────┴───────────┘

In [3]:
# Read them all in!
filenames = glob.glob(f"{DIR}/*.depth.txt")

dflist = []
for i, n in enumerate(filenames):
    if i % 100 == 0:
        print(f"{i} of {len(filenames)}")
    n = os.path.basename(n)
    metag, _, species, _ = n.split('.', 3)
    dflist.append(read_depth_txt(metag, species))

depth_df = pl.concat(dflist)

print(f"read {len(filenames)} depth files.")

0 of 2000
100 of 2000
200 of 2000
300 of 2000
400 of 2000
500 of 2000
600 of 2000
700 of 2000
800 of 2000
900 of 2000
1000 of 2000
1100 of 2000
1200 of 2000
1300 of 2000
1400 of 2000
1500 of 2000
1600 of 2000
1700 of 2000
1800 of 2000
1900 of 2000
read 2000 depth files.

In [4]:
depth_df.filter(pl.col('depth_all').is_not_nan()).sort(by='depth_all', descending=True).filter(pl.col('depth_all') > 0.0)

shape: (153_799, 8)
┌─────────────┬──────────────┬──────────────┬──────┬──────┬──────────┬──────────────┬──────────────┐
│ metag       ┆ species      ┆ gene         ┆ len  ┆ hits ┆ breadth  ┆ depth_all    ┆ depth_cov    │
│ ---         ┆ ---          ┆ ---          ┆ ---  ┆ ---  ┆ ---      ┆ ---          ┆ ---          │
│ str         ┆ str          ┆ str          ┆ u32  ┆ u32  ┆ f64      ┆ f64          ┆ f64          │
╞═════════════╪══════════════╪══════════════╪══════╪══════╪══════════╪══════════════╪══════════════╡
│ SRR14369134 ┆ s__Sodaliphi ┆ JHPFMEME_009 ┆ 702  ┆ 702  ┆ 1.0      ┆ 17800.038462 ┆ 17800.038462 │
│             ┆ lus          ┆ 05           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp004557565  ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR11489750 ┆ s__Sodaliphi ┆ JHPFMEME_009 ┆ 702  ┆ 702  ┆ 1.0      ┆ 12280.894587 ┆ 12280.894587 │
│             ┆ lus          ┆ 05           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp004557565  ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR12795790 ┆ s__Sodaliphi ┆ JHPFMEME_009 ┆ 702  ┆ 702  ┆ 1.0      ┆ 8948.836182  ┆ 8948.836182  │
│             ┆ lus          ┆ 05           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp004557565  ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR10209683 ┆ s__Mogibacte ┆ AAOFCIJB_002 ┆ 1119 ┆ 1119 ┆ 1.0      ┆ 8170.679178  ┆ 8170.679178  │
│             ┆ rium_A       ┆ 77           ┆      ┆      ┆          ┆              ┆              │
│             ┆ kristiansen… ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR17241663 ┆ s__Mogibacte ┆ JMKEGFFJ_013 ┆ 1899 ┆ 1899 ┆ 1.0      ┆ 7469.317536  ┆ 7469.317536  │
│             ┆ rium_A       ┆ 26           ┆      ┆      ┆          ┆              ┆              │
│             ┆ kristiansen… ┆              ┆      ┆      ┆          ┆              ┆              │
│ …           ┆ …            ┆ …            ┆ …    ┆ …    ┆ …        ┆ …            ┆ …            │
│ ERR3211876  ┆ s__Gemmiger  ┆ PMKFNJDI_004 ┆ 3072 ┆ 4    ┆ 0.001302 ┆ 0.001302     ┆ 1.0          │
│             ┆ qucibialis   ┆ 77           ┆      ┆      ┆          ┆              ┆              │
│ SRR8655118  ┆ s__Cryptobac ┆ CMHHCIHA_008 ┆ 2016 ┆ 2    ┆ 0.000992 ┆ 0.000992     ┆ 1.0          │
│             ┆ teroides     ┆ 93           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp9005469…   ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR11124687 ┆ s__Prevotell ┆ OPHKNFIJ_008 ┆ 2094 ┆ 2    ┆ 0.000955 ┆ 0.000955     ┆ 1.0          │
│             ┆ a            ┆ 63           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp002251295  ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR14369255 ┆ s__Cryptobac ┆ OIJDNDLK_007 ┆ 1074 ┆ 1    ┆ 0.000931 ┆ 0.000931     ┆ 1.0          │
│             ┆ teroides     ┆ 02           ┆      ┆      ┆          ┆              ┆              │
│             ┆ sp9005469…   ┆              ┆      ┆      ┆          ┆              ┆              │
│ SRR11126273 ┆ s__UBA2868   ┆ BJBPFFKB_014 ┆ 3480 ┆ 1    ┆ 0.000287 ┆ 0.000287     ┆ 1.0          │
│             ┆ sp004552595  ┆ 40           ┆      ┆      ┆          ┆              ┆              │
└─────────────┴──────────────┴──────────────┴──────┴──────┴──────────┴──────────────┴──────────────┘

## Summarize our mapping breadth results across all the metagenomes

In [5]:
# require 10% of each gene to be covered by at least one read
BREADTH_CUTOFF = 0.1

In [6]:
# aggregate across all metagenomes;
# calculate fraction of metagenomes for which gene mapping exceeds our breadth cutoff
agg_df = depth_df.group_by(['species', 'gene']).agg(
    # get fraction of columns where breadth is greater than cutoff as 'f'
    ((pl.col("breadth") >= BREADTH_CUTOFF).sum() / pl.col("breadth").len()).alias("f"),
#    (pl.col("depth").filter(pl.col("depth").is_not_nan()).mean()),
)
agg_df

shape: (1_903, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Cryptobacteroides sp0004326… ┆ PLMAOHLG_00421 ┆ 0.59 │
│ s__Colivicinus sp002299675      ┆ OKBMHBJH_00928 ┆ 0.62 │
│ s__Sodaliphilus sp004557565     ┆ MOGKDPAH_00816 ┆ 0.91 │
│ s__Sodaliphilus sp004557565     ┆ DAJNDEIP_01218 ┆ 0.93 │
│ s__Sodaliphilus sp004557565     ┆ ADJFOMCG_01030 ┆ 0.84 │
│ …                               ┆ …              ┆ …    │
│ s__Prevotella sp000434975       ┆ AEONIABF_01853 ┆ 0.77 │
│ s__Prevotella sp000434975       ┆ PAPCDFOC_01977 ┆ 0.85 │
│ s__Gemmiger qucibialis          ┆ OHFELPLO_01144 ┆ 0.2  │
│ s__Sodaliphilus sp004557565     ┆ FCNACBOG_00332 ┆ 0.92 │
│ s__Cryptobacteroides sp9005469… ┆ BEKEPKDC_00417 ┆ 0.9  │
└─────────────────────────────────┴────────────────┴──────┘

In [11]:
# print information out by species
for species in sorted(agg_df['species'].unique()):
    print(species)
    foo_df = agg_df.filter(pl.col("species") == species)
    foo_df = foo_df.sort(by='f', descending=True).filter(pl.col('f') > 0.8)
    print(foo_df)

    top50_names = set(foo_df.head(50)['gene'].to_list())

    outfile = f'../outputs.cds/singleclust/{species}.cds.min50.dedup.top50.fa'
    print(outfile)
    outfp = open(outfile, 'wt')
    for record in screed.open(f'../outputs.cds/singleclust/{species}.cds3.min50.dedup.fa'):
        name = record.name.split(' ')[0]
        if name in top50_names:
            top50_names.remove(name)
            outfp.write(f'>{record.name}\n{record.sequence}\n')
    assert not top50_names
    outfp.close()

    outfile2 = f'../outputs.cds/singleclust/{species}.cds.min50.dedup.top50.csv'
    print(outfile2)
    outfp = open(outfile2, 'w', newline='')
    w = csv.writer(outfp)

    for name in foo_df.head(50)['gene'].to_list():
        w.writerow(['0', '0', species, name, "(not reviewed)"])
    outfp.close()

s__Bariatricus sp004560705
shape: (14, 3)
┌────────────────────────────┬────────────────┬──────┐
│ species                    ┆ gene           ┆ f    │
│ ---                        ┆ ---            ┆ ---  │
│ str                        ┆ str            ┆ f64  │
╞════════════════════════════╪════════════════╪══════╡
│ s__Bariatricus sp004560705 ┆ CHOLCMOC_00863 ┆ 0.97 │
│ s__Bariatricus sp004560705 ┆ LEHFNBLN_00701 ┆ 0.95 │
│ s__Bariatricus sp004560705 ┆ LEHFNBLN_02301 ┆ 0.93 │
│ s__Bariatricus sp004560705 ┆ NDCIOGGG_00214 ┆ 0.9  │
│ s__Bariatricus sp004560705 ┆ FMMMFAAO_00746 ┆ 0.89 │
│ …                          ┆ …              ┆ …    │
│ s__Bariatricus sp004560705 ┆ IEPLHDOE_02248 ┆ 0.82 │
│ s__Bariatricus sp004560705 ┆ NOACAEKI_00860 ┆ 0.82 │
│ s__Bariatricus sp004560705 ┆ EMNHIHKA_01693 ┆ 0.82 │
│ s__Bariatricus sp004560705 ┆ ELOEBFJM_01459 ┆ 0.81 │
│ s__Bariatricus sp004560705 ┆ NGBMPMHL_00028 ┆ 0.81 │
└────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Bariatricus sp004560705.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Bariatricus sp004560705.cds.min50.dedup.top50.csv
s__Colivicinus sp002299675
shape: (18, 3)
┌────────────────────────────┬────────────────┬──────┐
│ species                    ┆ gene           ┆ f    │
│ ---                        ┆ ---            ┆ ---  │
│ str                        ┆ str            ┆ f64  │
╞════════════════════════════╪════════════════╪══════╡
│ s__Colivicinus sp002299675 ┆ GEJNMJHK_01170 ┆ 0.97 │
│ s__Colivicinus sp002299675 ┆ CJCMOHOO_00566 ┆ 0.89 │
│ s__Colivicinus sp002299675 ┆ MFJKOBHN_00700 ┆ 0.89 │
│ s__Colivicinus sp002299675 ┆ IHHGCNHF_01282 ┆ 0.87 │
│ s__Colivicinus sp002299675 ┆ LDCMLOKM_00609 ┆ 0.86 │
│ …                          ┆ …              ┆ …    │
│ s__Colivicinus sp002299675 ┆ MAEKDHDM_00310 ┆ 0.82 │
│ s__Colivicinus sp002299675 ┆ OKBMHBJH_00253 ┆ 0.81 │
│ s__Colivicinus sp002299675 ┆ HLAFBHBG_00423 ┆ 0.81 │
│ s__Colivicinus sp002299675 ┆ NPHOINMK_01102 ┆ 0.81 │
│ s__Colivicinus sp002299675 ┆ OKBMHBJH_00564 ┆ 0.81 │
└────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Colivicinus sp002299675.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Colivicinus sp002299675.cds.min50.dedup.top50.csv
s__Cryptobacteroides sp000432655
shape: (16, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Cryptobacteroides sp0004326… ┆ FCPPOLBJ_01097 ┆ 0.96 │
│ s__Cryptobacteroides sp0004326… ┆ FCPPOLBJ_01539 ┆ 0.94 │
│ s__Cryptobacteroides sp0004326… ┆ PGJBNNGM_01103 ┆ 0.9  │
│ s__Cryptobacteroides sp0004326… ┆ AINGCLHH_01781 ┆ 0.88 │
│ s__Cryptobacteroides sp0004326… ┆ FCPPOLBJ_01981 ┆ 0.88 │
│ …                               ┆ …              ┆ …    │
│ s__Cryptobacteroides sp0004326… ┆ JDIPOLOI_01075 ┆ 0.82 │
│ s__Cryptobacteroides sp0004326… ┆ BIBFGMOK_01065 ┆ 0.82 │
│ s__Cryptobacteroides sp0004326… ┆ FCPPOLBJ_01182 ┆ 0.82 │
│ s__Cryptobacteroides sp0004326… ┆ AINGCLHH_00714 ┆ 0.81 │
│ s__Cryptobacteroides sp0004326… ┆ BIBFGMOK_00552 ┆ 0.81 │
└─────────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Cryptobacteroides sp000432655.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Cryptobacteroides sp000432655.cds.min50.dedup.top50.csv
s__Cryptobacteroides sp000434935
shape: (24, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Cryptobacteroides sp0004349… ┆ KGJCAHGF_01031 ┆ 0.93 │
│ s__Cryptobacteroides sp0004349… ┆ DOLCGLJK_00979 ┆ 0.93 │
│ s__Cryptobacteroides sp0004349… ┆ NBGEPFAP_00285 ┆ 0.89 │
│ s__Cryptobacteroides sp0004349… ┆ LKCGFCMG_01869 ┆ 0.89 │
│ s__Cryptobacteroides sp0004349… ┆ EKFEBOAA_01312 ┆ 0.89 │
│ …                               ┆ …              ┆ …    │
│ s__Cryptobacteroides sp0004349… ┆ FCHBMNJF_01297 ┆ 0.81 │
│ s__Cryptobacteroides sp0004349… ┆ MGCIIDEG_02262 ┆ 0.81 │
│ s__Cryptobacteroides sp0004349… ┆ ADCODNMF_01281 ┆ 0.81 │
│ s__Cryptobacteroides sp0004349… ┆ EIGGHFPC_02121 ┆ 0.81 │
│ s__Cryptobacteroides sp0004349… ┆ DOLCGLJK_00897 ┆ 0.81 │
└─────────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Cryptobacteroides sp000434935.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Cryptobacteroides sp000434935.cds.min50.dedup.top50.csv
s__Cryptobacteroides sp034089285
shape: (70, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Cryptobacteroides sp0340892… ┆ JOICFBBB_00740 ┆ 0.96 │
│ s__Cryptobacteroides sp0340892… ┆ PAFOMHJE_00204 ┆ 0.96 │
│ s__Cryptobacteroides sp0340892… ┆ ALBNLPDA_00834 ┆ 0.94 │
│ s__Cryptobacteroides sp0340892… ┆ APPGPOOG_00561 ┆ 0.94 │
│ s__Cryptobacteroides sp0340892… ┆ HMMKHJPF_01362 ┆ 0.94 │
│ …                               ┆ …              ┆ …    │
│ s__Cryptobacteroides sp0340892… ┆ FELCFHKP_00315 ┆ 0.81 │
│ s__Cryptobacteroides sp0340892… ┆ NEGNLLKM_00470 ┆ 0.81 │
│ s__Cryptobacteroides sp0340892… ┆ IPLMGEAK_01875 ┆ 0.81 │
│ s__Cryptobacteroides sp0340892… ┆ CEGKJMLJ_01410 ┆ 0.81 │
│ s__Cryptobacteroides sp0340892… ┆ NEGNLLKM_00502 ┆ 0.81 │
└─────────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Cryptobacteroides sp034089285.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Cryptobacteroides sp034089285.cds.min50.dedup.top50.csv
s__Cryptobacteroides sp900546925
shape: (117, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Cryptobacteroides sp9005469… ┆ FIKGMHDC_00998 ┆ 0.94 │
│ s__Cryptobacteroides sp9005469… ┆ BDFOMKKK_00335 ┆ 0.92 │
│ s__Cryptobacteroides sp9005469… ┆ CMHHCIHA_00622 ┆ 0.92 │
│ s__Cryptobacteroides sp9005469… ┆ BEKEPKDC_00417 ┆ 0.9  │
│ s__Cryptobacteroides sp9005469… ┆ EHLNOCPD_00288 ┆ 0.89 │
│ …                               ┆ …              ┆ …    │
│ s__Cryptobacteroides sp9005469… ┆ CPBNAKKL_01128 ┆ 0.81 │
│ s__Cryptobacteroides sp9005469… ┆ FFGMIBGD_00294 ┆ 0.81 │
│ s__Cryptobacteroides sp9005469… ┆ FNIGJHLI_00173 ┆ 0.81 │
│ s__Cryptobacteroides sp9005469… ┆ LELOEEPG_00242 ┆ 0.81 │
│ s__Cryptobacteroides sp9005469… ┆ FOKFIHIM_00492 ┆ 0.81 │
└─────────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Cryptobacteroides sp900546925.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Cryptobacteroides sp900546925.cds.min50.dedup.top50.csv
s__Fimisoma sp002320005
shape: (1, 3)
┌─────────────────────────┬────────────────┬──────┐
│ species                 ┆ gene           ┆ f    │
│ ---                     ┆ ---            ┆ ---  │
│ str                     ┆ str            ┆ f64  │
╞═════════════════════════╪════════════════╪══════╡
│ s__Fimisoma sp002320005 ┆ JAOEKFJL_01590 ┆ 0.92 │
└─────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Fimisoma sp002320005.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Fimisoma sp002320005.cds.min50.dedup.top50.csv
s__Floccifex porci
shape: (0, 3)
┌─────────┬──────┬─────┐
│ species ┆ gene ┆ f   │
│ ---     ┆ ---  ┆ --- │
│ str     ┆ str  ┆ f64 │
╞═════════╪══════╪═════╡
└─────────┴──────┴─────┘
../outputs.cds/singleclust/s__Floccifex porci.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Floccifex porci.cds.min50.dedup.top50.csv
s__Gemmiger qucibialis
shape: (10, 3)
┌────────────────────────┬────────────────┬──────┐
│ species                ┆ gene           ┆ f    │
│ ---                    ┆ ---            ┆ ---  │
│ str                    ┆ str            ┆ f64  │
╞════════════════════════╪════════════════╪══════╡
│ s__Gemmiger qucibialis ┆ GLIPJGEI_00065 ┆ 0.94 │
│ s__Gemmiger qucibialis ┆ EANOHOOJ_01559 ┆ 0.92 │
│ s__Gemmiger qucibialis ┆ IPGJNJJC_00242 ┆ 0.91 │
│ s__Gemmiger qucibialis ┆ CLHLFGFN_00542 ┆ 0.91 │
│ s__Gemmiger qucibialis ┆ LAOGNEID_00570 ┆ 0.9  │
│ s__Gemmiger qucibialis ┆ AGHFCGHF_02266 ┆ 0.89 │
│ s__Gemmiger qucibialis ┆ DLCICKOP_02020 ┆ 0.85 │
│ s__Gemmiger qucibialis ┆ GOPMMJLD_01454 ┆ 0.85 │
│ s__Gemmiger qucibialis ┆ PEAPMGON_00222 ┆ 0.82 │
│ s__Gemmiger qucibialis ┆ EBFKGAGP_00060 ┆ 0.81 │
└────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Gemmiger qucibialis.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Gemmiger qucibialis.cds.min50.dedup.top50.csv
s__Holdemanella porci
shape: (0, 3)
┌─────────┬──────┬─────┐
│ species ┆ gene ┆ f   │
│ ---     ┆ ---  ┆ --- │
│ str     ┆ str  ┆ f64 │
╞═════════╪══════╪═════╡
└─────────┴──────┴─────┘
../outputs.cds/singleclust/s__Holdemanella porci.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Holdemanella porci.cds.min50.dedup.top50.csv
s__JALFVM01 sp022787145
shape: (0, 3)
┌─────────┬──────┬─────┐
│ species ┆ gene ┆ f   │
│ ---     ┆ ---  ┆ --- │
│ str     ┆ str  ┆ f64 │
╞═════════╪══════╪═════╡
└─────────┴──────┴─────┘
../outputs.cds/singleclust/s__JALFVM01 sp022787145.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__JALFVM01 sp022787145.cds.min50.dedup.top50.csv
s__Lactobacillus amylovorus
shape: (18, 3)
┌─────────────────────────────┬────────────────┬──────┐
│ species                     ┆ gene           ┆ f    │
│ ---                         ┆ ---            ┆ ---  │
│ str                         ┆ str            ┆ f64  │
╞═════════════════════════════╪════════════════╪══════╡
│ s__Lactobacillus amylovorus ┆ CPLGDGDL_01434 ┆ 0.92 │
│ s__Lactobacillus amylovorus ┆ BBOFCOCJ_01349 ┆ 0.9  │
│ s__Lactobacillus amylovorus ┆ HPBCBKPJ_01887 ┆ 0.89 │
│ s__Lactobacillus amylovorus ┆ OMBJBIHD_01711 ┆ 0.87 │
│ s__Lactobacillus amylovorus ┆ PGPELEHO_01832 ┆ 0.87 │
│ …                           ┆ …              ┆ …    │
│ s__Lactobacillus amylovorus ┆ JOFDALNO_00602 ┆ 0.82 │
│ s__Lactobacillus amylovorus ┆ CPKOPDLF_00550 ┆ 0.82 │
│ s__Lactobacillus amylovorus ┆ IAOGNCPA_00195 ┆ 0.81 │
│ s__Lactobacillus amylovorus ┆ LEAIKLIG_01457 ┆ 0.81 │
│ s__Lactobacillus amylovorus ┆ NKKPHFMM_01729 ┆ 0.81 │
└─────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Lactobacillus amylovorus.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Lactobacillus amylovorus.cds.min50.dedup.top50.csv
s__Mogibacterium_A kristiansenii
shape: (3, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Mogibacterium_A kristiansen… ┆ JMKEGFFJ_01326 ┆ 1.0  │
│ s__Mogibacterium_A kristiansen… ┆ AAOFCIJB_00277 ┆ 1.0  │
│ s__Mogibacterium_A kristiansen… ┆ NGANNMPO_01097 ┆ 0.87 │
└─────────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Mogibacterium_A kristiansenii.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Mogibacterium_A kristiansenii.cds.min50.dedup.top50.csv
s__Ornithospirochaeta sp022785155
shape: (43, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Ornithospirochaeta sp022785… ┆ DIHHAJIK_01286 ┆ 0.92 │
│ s__Ornithospirochaeta sp022785… ┆ LKMFJOKJ_01452 ┆ 0.92 │
│ s__Ornithospirochaeta sp022785… ┆ BCHPCDPL_01462 ┆ 0.92 │
│ s__Ornithospirochaeta sp022785… ┆ AOCKAKOA_02189 ┆ 0.9  │
│ s__Ornithospirochaeta sp022785… ┆ DIHHAJIK_00954 ┆ 0.9  │
│ …                               ┆ …              ┆ …    │
│ s__Ornithospirochaeta sp022785… ┆ LKMFJOKJ_00632 ┆ 0.81 │
│ s__Ornithospirochaeta sp022785… ┆ BDAFNFPJ_01589 ┆ 0.81 │
│ s__Ornithospirochaeta sp022785… ┆ BCHPCDPL_00203 ┆ 0.81 │
│ s__Ornithospirochaeta sp022785… ┆ BCHPCDPL_00410 ┆ 0.81 │
│ s__Ornithospirochaeta sp022785… ┆ LKMFJOKJ_01321 ┆ 0.81 │
└─────────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Ornithospirochaeta sp022785155.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Ornithospirochaeta sp022785155.cds.min50.dedup.top50.csv
s__Phascolarctobacterium_A succinatutens
shape: (5, 3)
┌─────────────────────────────────┬────────────────┬──────┐
│ species                         ┆ gene           ┆ f    │
│ ---                             ┆ ---            ┆ ---  │
│ str                             ┆ str            ┆ f64  │
╞═════════════════════════════════╪════════════════╪══════╡
│ s__Phascolarctobacterium_A suc… ┆ CNENGHLA_00658 ┆ 0.96 │
│ s__Phascolarctobacterium_A suc… ┆ CNENGHLA_01260 ┆ 0.91 │
│ s__Phascolarctobacterium_A suc… ┆ LDBAILDD_01769 ┆ 0.9  │
│ s__Phascolarctobacterium_A suc… ┆ GGLHANJG_01414 ┆ 0.88 │
│ s__Phascolarctobacterium_A suc… ┆ DHJLCIIK_01145 ┆ 0.84 │
└─────────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Phascolarctobacterium_A succinatutens.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Phascolarctobacterium_A succinatutens.cds.min50.dedup.top50.csv
s__Prevotella sp000434975
shape: (75, 3)
┌───────────────────────────┬────────────────┬──────┐
│ species                   ┆ gene           ┆ f    │
│ ---                       ┆ ---            ┆ ---  │
│ str                       ┆ str            ┆ f64  │
╞═══════════════════════════╪════════════════╪══════╡
│ s__Prevotella sp000434975 ┆ HGGBKJHA_00064 ┆ 0.93 │
│ s__Prevotella sp000434975 ┆ AJCJGFNH_00477 ┆ 0.93 │
│ s__Prevotella sp000434975 ┆ BAIAEPON_01639 ┆ 0.92 │
│ s__Prevotella sp000434975 ┆ PDHLFJAL_00903 ┆ 0.92 │
│ s__Prevotella sp000434975 ┆ MLIECJNI_00172 ┆ 0.92 │
│ …                         ┆ …              ┆ …    │
│ s__Prevotella sp000434975 ┆ LNBCJMFF_01780 ┆ 0.81 │
│ s__Prevotella sp000434975 ┆ IBGIKLDL_02009 ┆ 0.81 │
│ s__Prevotella sp000434975 ┆ POCFJPKP_00953 ┆ 0.81 │
│ s__Prevotella sp000434975 ┆ JDKJHEGC_01287 ┆ 0.81 │
│ s__Prevotella sp000434975 ┆ DKNPLDGH_00708 ┆ 0.81 │
└───────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Prevotella sp000434975.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Prevotella sp000434975.cds.min50.dedup.top50.csv
s__Prevotella sp002251295
shape: (77, 3)
┌───────────────────────────┬────────────────┬──────┐
│ species                   ┆ gene           ┆ f    │
│ ---                       ┆ ---            ┆ ---  │
│ str                       ┆ str            ┆ f64  │
╞═══════════════════════════╪════════════════╪══════╡
│ s__Prevotella sp002251295 ┆ IPDEFMND_01992 ┆ 0.95 │
│ s__Prevotella sp002251295 ┆ COCKKAPE_02026 ┆ 0.93 │
│ s__Prevotella sp002251295 ┆ KINAFDOL_01550 ┆ 0.92 │
│ s__Prevotella sp002251295 ┆ GFALEAHI_01277 ┆ 0.91 │
│ s__Prevotella sp002251295 ┆ KPACIEHJ_00390 ┆ 0.91 │
│ …                         ┆ …              ┆ …    │
│ s__Prevotella sp002251295 ┆ OAHOCONN_01023 ┆ 0.81 │
│ s__Prevotella sp002251295 ┆ OAHOCONN_01297 ┆ 0.81 │
│ s__Prevotella sp002251295 ┆ OEDAEGJB_01922 ┆ 0.81 │
│ s__Prevotella sp002251295 ┆ GDBLKLPM_00824 ┆ 0.81 │
│ s__Prevotella sp002251295 ┆ KEAKGAAF_02352 ┆ 0.81 │
└───────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Prevotella sp002251295.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Prevotella sp002251295.cds.min50.dedup.top50.csv
s__Roseburia inulinivorans
shape: (4, 3)
┌────────────────────────────┬────────────────┬──────┐
│ species                    ┆ gene           ┆ f    │
│ ---                        ┆ ---            ┆ ---  │
│ str                        ┆ str            ┆ f64  │
╞════════════════════════════╪════════════════╪══════╡
│ s__Roseburia inulinivorans ┆ HGAHBKMD_00300 ┆ 0.84 │
│ s__Roseburia inulinivorans ┆ HGAHBKMD_00299 ┆ 0.83 │
│ s__Roseburia inulinivorans ┆ HGAHBKMD_00261 ┆ 0.83 │
│ s__Roseburia inulinivorans ┆ HGAHBKMD_00273 ┆ 0.81 │
└────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Roseburia inulinivorans.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Roseburia inulinivorans.cds.min50.dedup.top50.csv
s__Sodaliphilus sp004557565
shape: (497, 3)
┌─────────────────────────────┬────────────────┬──────┐
│ species                     ┆ gene           ┆ f    │
│ ---                         ┆ ---            ┆ ---  │
│ str                         ┆ str            ┆ f64  │
╞═════════════════════════════╪════════════════╪══════╡
│ s__Sodaliphilus sp004557565 ┆ JHPFMEME_00905 ┆ 0.98 │
│ s__Sodaliphilus sp004557565 ┆ COJGPLPN_01769 ┆ 0.96 │
│ s__Sodaliphilus sp004557565 ┆ JJHEGIOA_01813 ┆ 0.96 │
│ s__Sodaliphilus sp004557565 ┆ MPEKMBOO_01380 ┆ 0.96 │
│ s__Sodaliphilus sp004557565 ┆ HENFICJG_01772 ┆ 0.96 │
│ …                           ┆ …              ┆ …    │
│ s__Sodaliphilus sp004557565 ┆ MKOAJGNL_01972 ┆ 0.81 │
│ s__Sodaliphilus sp004557565 ┆ JPBNNJKP_01057 ┆ 0.81 │
│ s__Sodaliphilus sp004557565 ┆ OLAJAFEB_01647 ┆ 0.81 │
│ s__Sodaliphilus sp004557565 ┆ GEGNICLP_00271 ┆ 0.81 │
│ s__Sodaliphilus sp004557565 ┆ LFLAOHMB_01227 ┆ 0.81 │
└─────────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__Sodaliphilus sp004557565.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__Sodaliphilus sp004557565.cds.min50.dedup.top50.csv
s__UBA2868 sp004552595
shape: (5, 3)
┌────────────────────────┬────────────────┬──────┐
│ species                ┆ gene           ┆ f    │
│ ---                    ┆ ---            ┆ ---  │
│ str                    ┆ str            ┆ f64  │
╞════════════════════════╪════════════════╪══════╡
│ s__UBA2868 sp004552595 ┆ GHILBDOG_00591 ┆ 0.97 │
│ s__UBA2868 sp004552595 ┆ KMEHCMKH_00746 ┆ 0.88 │
│ s__UBA2868 sp004552595 ┆ IPIMNMMB_00240 ┆ 0.82 │
│ s__UBA2868 sp004552595 ┆ IEHIAHIF_00466 ┆ 0.82 │
│ s__UBA2868 sp004552595 ┆ GLNAKBGL_01080 ┆ 0.82 │
└────────────────────────┴────────────────┴──────┘
../outputs.cds/singleclust/s__UBA2868 sp004552595.cds.min50.dedup.top50.fa
../outputs.cds/singleclust/s__UBA2868 sp004552595.cds.min50.dedup.top50.csv

## Export mapping abundance data to a CSV, after merging with `species-genes.csv`

In [24]:
species_genes_df = (pl.read_csv('../outputs.cds/singleclust/species-genes.csv')
    .filter(pl.col("good") == 1)
    .with_columns(pl.col('gene_name').alias('gene'))
    .select(["anchor", "gene", "species", "description"])
)

species_genes_df

shape: (69, 4)
┌────────┬────────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ anchor ┆ gene           ┆ species                         ┆ description                     │
│ ---    ┆ ---            ┆ ---                             ┆ ---                             │
│ i64    ┆ str            ┆ str                             ┆ str                             │
╞════════╪════════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ 1      ┆ CNENGHLA_01260 ┆ s__Phascolarctobacterium_A suc… ┆ BLAST match to hydrogenase lar… │
│ 0      ┆ EHOAPHDI_01174 ┆ s__Phascolarctobacterium_A suc… ┆ BLAST match to protein phospha… │
│ 0      ┆ CNENGHLA_00658 ┆ s__Phascolarctobacterium_A suc… ┆ BLAST match to 4-hydroxy-3-met… │
│ 0      ┆ IFIBFMPA_00800 ┆ s__Phascolarctobacterium_A suc… ┆ BLAST match to  2-isopropylmal… │
│ 0      ┆ BBOFCOCJ_01349 ┆ s__Lactobacillus amylovorus     ┆ BLAST match to peptidase T [La… │
│ …      ┆ …              ┆ …                               ┆ …                               │
│ 1      ┆ JBPBJODD_00501 ┆ s__Cryptobacteroides sp0004349… ┆ hypothetical protein [Bacteroi… │
│ 0      ┆ KHMCBGLI_01458 ┆ s__Cryptobacteroides sp0004349… ┆ putative uncharacterized prote… │
│ 0      ┆ FCHBMNJF_01297 ┆ s__Cryptobacteroides sp0004349… ┆ ATP-binding protein [Bacteroid… │
│ 1      ┆ IIAENJBH_00799 ┆ s__Floccifex porci              ┆ anaerobic ribonucleoside-triph… │
│ 1      ┆ JBNOCHBL_00669 ┆ s__Fimisoma sp002320005         ┆ PEP/pyruvate-binding domain-co… │
└────────┴────────────────┴─────────────────────────────────┴─────────────────────────────────┘

In [25]:
merge_df = depth_df.join(species_genes_df, on=["species", "gene"], how='inner')
merge_df

shape: (6_500, 10)
┌─────────────┬─────────────┬─────────────┬──────┬───┬───────────┬───────────┬────────┬────────────┐
│ metag       ┆ species     ┆ gene        ┆ len  ┆ … ┆ depth_all ┆ depth_cov ┆ anchor ┆ descriptio │
│ ---         ┆ ---         ┆ ---         ┆ ---  ┆   ┆ ---       ┆ ---       ┆ ---    ┆ n          │
│ str         ┆ str         ┆ str         ┆ u32  ┆   ┆ f64       ┆ f64       ┆ i64    ┆ ---        │
│             ┆             ┆             ┆      ┆   ┆           ┆           ┆        ┆ str        │
╞═════════════╪═════════════╪═════════════╪══════╪═══╪═══════════╪═══════════╪════════╪════════════╡
│ SRR17241485 ┆ s__Phascola ┆ CNENGHLA_00 ┆ 1179 ┆ … ┆ 3.201866  ┆ 9.856397  ┆ 0      ┆ BLAST      │
│             ┆ rctobacteri ┆ 658         ┆      ┆   ┆           ┆           ┆        ┆ match to   │
│             ┆ um_A suc…   ┆             ┆      ┆   ┆           ┆           ┆        ┆ 4-hydroxy- │
│             ┆             ┆             ┆      ┆   ┆           ┆           ┆        ┆ 3-met…     │
│ SRR17241485 ┆ s__Phascola ┆ CNENGHLA_01 ┆ 1398 ┆ … ┆ 3.907725  ┆ 10.023853 ┆ 1      ┆ BLAST      │
│             ┆ rctobacteri ┆ 260         ┆      ┆   ┆           ┆           ┆        ┆ match to   │
│             ┆ um_A suc…   ┆             ┆      ┆   ┆           ┆           ┆        ┆ hydrogenas │
│             ┆             ┆             ┆      ┆   ┆           ┆           ┆        ┆ e lar…     │
│ ERR3211974  ┆ s__UBA2868  ┆ IPIMNMMB_00 ┆ 1995 ┆ … ┆ 0.075689  ┆ 1.0       ┆ 0      ┆ type I DNA │
│             ┆ sp004552595 ┆ 240         ┆      ┆   ┆           ┆           ┆        ┆ topoisomer │
│             ┆             ┆             ┆      ┆   ┆           ┆           ┆        ┆ ase [Lach… │
│ ERR3211974  ┆ s__UBA2868  ┆ IEHIAHIF_00 ┆ 1431 ┆ … ┆ 0.05311   ┆ 1.0       ┆ 0      ┆ L-arabinos │
│             ┆ sp004552595 ┆ 466         ┆      ┆   ┆           ┆           ┆        ┆ e          │
│             ┆             ┆             ┆      ┆   ┆           ┆           ┆        ┆ isomerase  │
│             ┆             ┆             ┆      ┆   ┆           ┆           ┆        ┆ [Lachnos…  │
│ ERR3211974  ┆ s__UBA2868  ┆ KMEHCMKH_00 ┆ 1083 ┆ … ┆ 0.43675   ┆ 1.506369  ┆ 1      ┆ multiple   │
│             ┆ sp004552595 ┆ 746         ┆      ┆   ┆           ┆           ┆        ┆ monosaccha │
│             ┆             ┆             ┆      ┆   ┆           ┆           ┆        ┆ ride ABC   │
│             ┆             ┆             ┆      ┆   ┆           ┆           ┆        ┆ tr…        │
│ …           ┆ …           ┆ …           ┆ …    ┆ … ┆ …         ┆ …         ┆ …      ┆ …          │
│ ERR1135304  ┆ s__Prevotel ┆ GFALEAHI_01 ┆ 2526 ┆ … ┆ 44.572842 ┆ 44.75     ┆ 1      ┆ YfnO       │
│             ┆ la          ┆ 277         ┆      ┆   ┆           ┆           ┆        ┆            │
│             ┆ sp002251295 ┆             ┆      ┆   ┆           ┆           ┆        ┆            │
│ ERR1135304  ┆ s__Prevotel ┆ MNKNIMJG_02 ┆ 186  ┆ … ┆ 34.532258 ┆ 34.532258 ┆ 0      ┆ hypothetic │
│             ┆ la          ┆ 022         ┆      ┆   ┆           ┆           ┆        ┆ al         │
│             ┆ sp002251295 ┆             ┆      ┆   ┆           ┆           ┆        ┆            │
│ ERR1135304  ┆ s__Prevotel ┆ KINAFDOL_01 ┆ 2604 ┆ … ┆ 32.506144 ┆ 38.82844  ┆ 0      ┆ transcript │
│             ┆ la          ┆ 550         ┆      ┆   ┆           ┆           ┆        ┆ ion-repair │
│             ┆ sp002251295 ┆             ┆      ┆   ┆           ┆           ┆        ┆ coupling … │
│ ERR1135304  ┆ s__Prevotel ┆ COCKKAPE_02 ┆ 1152 ┆ … ┆ 8.030382  ┆ 8.030382  ┆ 0      ┆ polysaccha │
│             ┆ la          ┆ 026         ┆      ┆   ┆           ┆           ┆        ┆ ride biosy │
│             ┆ sp002251295 ┆             ┆      ┆   ┆           ┆           ┆        ┆ nthesis    │
│             ┆             ┆             ┆      ┆   ┆           ┆           ┆        ┆ C-…        │
│ ERR1135304  ┆ s__Prevotel ┆ KPACIEHJ_00 ┆ 1200 ┆ … ┆ 30.219167 ┆ 30.219167 ┆ 0      ┆ DUF4302    │
│             ┆ la          ┆ 390         ┆      ┆   ┆           ┆           ┆        ┆ protein    │
│             ┆ sp002251295 ┆             ┆      ┆   ┆           ┆           ┆        ┆            │
└─────────────┴─────────────┴─────────────┴──────┴───┴───────────┴───────────┴────────┴────────────┘

In [26]:
merge_df.write_csv('../outputs.cds/cds3-genes/mapping-coverage.csv')