In [1]:
import polars as pl
import glob
import os.path

In [26]:
SCALED=1000
HASH_THRESHOLD=int(20000 / SCALED)
CONTAINMENT_THRESHOLD=0.01


#CSVPATH=f'../outputs.mapping/cds/singlehash.k21/outputs.3216.min{MIN}/manysearch.3216.csv'
CSVPATH=f'/home/ctbrown/scratch3/2025-workflow-core99/outputs.mapping/cds3/manysearch.cds3.3216.csv'

In [27]:
CORENAMES = set([ x.strip() for x in open('../inputs.mapping/names.list') ])

In [28]:
dflist = []
#ms_filenames = glob.glob('../manysearch-3216/*.cds.x.3216.manysearch.csv')
ms_filenames = glob.glob(CSVPATH)
for filename in ms_filenames:
    print(os.path.basename(filename))
    df = pl.read_csv(filename)
    dflist.append(df)

df = pl.concat(dflist)

manysearch.cds3.3216.csv

In [29]:
df

shape: (79_366, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Holdem ┆ 398766a16 ┆ SRR111264 ┆ 0.012257  ┆ … ┆ 0.721726  ┆ 0.810905  ┆ 30        ┆ 917220   │
│ anella    ┆ d18d486ff ┆ 13        ┆           ┆   ┆           ┆           ┆           ┆          │
│ porci     ┆ 57f019d26 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 4e4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Fimiso ┆ 019f828d6 ┆ SRR111264 ┆ 0.055435  ┆ … ┆ 0.780106  ┆ 0.871325  ┆ 134       ┆ 917220   │
│ ma sp0023 ┆ 4f7de39e3 ┆ 13        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 20005     ┆ cf407b3f3 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ d15…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__JALFVM ┆ 6e456de50 ┆ SRR111264 ┆ 0.001776  ┆ … ┆ 0.668192  ┆ 0.739645  ┆ 7         ┆ 917220   │
│ 01 sp0227 ┆ 4903038c2 ┆ 13        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 87145     ┆ 51145eeed ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 987…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ b8c6bbf95 ┆ SRR111264 ┆ 0.047307  ┆ … ┆ 0.769517  ┆ 0.864771  ┆ 100       ┆ 917220   │
│ larctobac ┆ 60cfc0876 ┆ 13        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 87eb69f00 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ b1c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Rumino ┆ 1334e4747 ┆ SRR111264 ┆ 0.000833  ┆ … ┆ 0.633089  ┆ 0.713464  ┆ 3         ┆ 917220   │
│ coccoides ┆ b950d31e4 ┆ 13        ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp9027668 ┆ 4e3448e8b ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 85        ┆ 0fa…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__UBA286 ┆ 9b398f77a ┆ ERR113546 ┆ 0.389427  ┆ … ┆ 0.843122  ┆ 0.956085  ┆ 24041     ┆ 4610214  │
│ 8 sp00455 ┆ 804ccf5d9 ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2595      ┆ 1548a2f8e ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 61c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Mogiba ┆ a6063c096 ┆ ERR113546 ┆ 0.012404  ┆ … ┆ 0.704668  ┆ 0.811366  ┆ 99        ┆ 4610214  │
│ cterium_A ┆ 2c975db51 ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│ kristians ┆ 4497f2715 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ en…       ┆ 11e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Crypto ┆ 80c1ce43c ┆ ERR113546 ┆ 0.114496  ┆ … ┆ 0.793401  ┆ 0.901946  ┆ 1189      ┆ 4610214  │
│ bacteroid ┆ 8dff68ff8 ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│ es sp9005 ┆ ec3e45dae ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 469…      ┆ 136…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Sodali ┆ 01b84a101 ┆ ERR113546 ┆ 0.147304  ┆ … ┆ 0.814036  ┆ 0.912833  ┆ 5189      ┆ 4610214  │
│ philus    ┆ 775aec06b ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp0045575 ┆ 80aef75f7 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 65        ┆ a9b…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Ventri ┆ 13e132d6b ┆ ERR113546 ┆ 0.050817  ┆ … ┆ 0.728905  ┆ 0.867723  ┆ 38        ┆ 4610214  │
│ cola sp01 ┆ d1eb6b5ae ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7937505   ┆ eb27ad0b6 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ bab…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [30]:
df.sort(by='intersect_hashes').filter(pl.col("intersect_hashes") < 20)

shape: (20_716, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Rumino ┆ 1334e4747 ┆ SRR111264 ┆ 0.000833  ┆ … ┆ 0.633089  ┆ 0.713464  ┆ 3         ┆ 917220   │
│ coccoides ┆ b950d31e4 ┆ 13        ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp9027668 ┆ 4e3448e8b ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 85        ┆ 0fa…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Blauti ┆ 2d4c0d183 ┆ SRR111264 ┆ 0.001305  ┆ … ┆ 0.640797  ┆ 0.72888   ┆ 1         ┆ 917220   │
│ a_A sp945 ┆ 352faea54 ┆ 13        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 872375    ┆ d9921b1c3 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 1ed…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 8c3d1fa61 ┆ SRR111264 ┆ 0.000233  ┆ … ┆ 0.612114  ┆ 0.671514  ┆ 1         ┆ 917220   │
│ larctobac ┆ d73093ded ┆ 13        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 0c14d4577 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 909…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Rumino ┆ 1334e4747 ┆ SRR111247 ┆ 0.000833  ┆ … ┆ 0.6324    ┆ 0.713464  ┆ 1         ┆ 1233731  │
│ coccoides ┆ b950d31e4 ┆ 21        ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp9027668 ┆ 4e3448e8b ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 85        ┆ 0fa…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Blauti ┆ 2d4c0d183 ┆ SRR111247 ┆ 0.001305  ┆ … ┆ 0.640108  ┆ 0.72888   ┆ 1         ┆ 1233731  │
│ a_A sp945 ┆ 352faea54 ┆ 21        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 872375    ┆ d9921b1c3 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 1ed…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__Phasco ┆ 8c3d1fa61 ┆ SRR172416 ┆ 0.004435  ┆ … ┆ 0.671224  ┆ 0.772588  ┆ 47        ┆ 17824676 │
│ larctobac ┆ d73093ded ┆ 11        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 0c14d4577 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 909…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__CAG-46 ┆ dbf18ece4 ┆ ERR113526 ┆ 0.020675  ┆ … ┆ 0.712873  ┆ 0.831348  ┆ 20        ┆ 4237153  │
│ 5 sp00043 ┆ 4eabc0166 ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3755      ┆ c4320733d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ea7…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bifido ┆ 79dff0ffe ┆ SRR114897 ┆ 0.006494  ┆ … ┆ 0.686413  ┆ 0.786742  ┆ 21        ┆ 11896321 │
│ bacterium ┆ f2a3cac02 ┆ 51        ┆           ┆   ┆           ┆           ┆           ┆          │
│ thermacid ┆ 68d3a69a6 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ op…       ┆ 724…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__UBA286 ┆ 9b398f77a ┆ SRR114897 ┆ 0.003016  ┆ … ┆ 0.672309  ┆ 0.758534  ┆ 24        ┆ 11896321 │
│ 8 sp00455 ┆ 804ccf5d9 ┆ 51        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2595      ┆ 1548a2f8e ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 61c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__CAG-26 ┆ 078c4569f ┆ SRR172415 ┆ 0.043578  ┆ … ┆ 0.715069  ┆ 0.861397  ┆ 28        ┆ 18860587 │
│ 9 sp01484 ┆ 257f75356 ┆ 08        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6485      ┆ 832c47c16 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 808…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [31]:
len(df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD))

58650

In [33]:
for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent', descending=True).iter_rows(named=True):
    name = row['query_name']
    if name in CORENAMES:
        name = '** ' + name
    print(f"{row['percent']:.1f}% {name} ")

99.0% ** s__Sodaliphilus sp004557565
98.5% ** s__Lactobacillus amylovorus
97.5% ** s__Cryptobacteroides sp900546925
97.1% ** s__Fimisoma sp002320005
97.0% ** s__Mogibacterium_A kristiansenii
96.7% ** s__UBA2868 sp004552595
96.4% ** s__Prevotella sp002251295
96.3% ** s__JAFBIX01 sp021531895
95.7% ** s__Bariatricus sp004560705
93.8% ** s__Prevotella sp000434975
90.6% ** s__JALFVM01 sp022787145
90.1% ** s__Holdemanella porci
87.6% ** s__Phascolarctobacterium_A succinatutens
82.7% ** s__Gemmiger qucibialis
77.6% s__UMGS1225 sp034086705
77.1% ** s__Roseburia inulinivorans
57.2% s__Ruminococcus_C sp000433635
52.1% s__SIG351 sp945918795
46.6% s__Bifidobacterium thermacidophilum
34.5% s__Blautia_A sp945872375
34.3% s__Ventricola sp017937505
34.1% s__CAG-873 sp016302215
28.8% s__CAG-269 sp014846485
22.4% s__Phascolarctobacterium_A succinatutens_B
20.6% s__CAG-465 sp000433755
19.6% s__Ruminococcoides sp902766885

In [8]:
for row in df.filter(pl.col("containment") >= CONTAINMENT_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    print(f"{row['percent']:.1f}% {row['query_name']} ")

78.9% s__JALFVM01 sp022787145
80.6% s__Roseburia inulinivorans
88.6% s__Holdemanella porci
89.0% s__Fimisoma sp002320005
92.8% s__UBA2868 sp004552595
96.2% s__Gemmiger qucibialis
97.3% s__Cryptobacteroides sp900546925
97.5% s__Prevotella sp000434975
97.8% s__Phascolarctobacterium_A succinatutens
98.3% s__Prevotella sp002251295
98.4% s__Bariatricus sp004560705
99.1% s__Sodaliphilus sp004557565
99.6% s__Lactobacillus amylovorus
99.8% s__Mogibacterium_A kristiansenii

In [9]:
df

shape: (42_511, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Gemmig ┆ d69eaa5dc ┆ SRR111839 ┆ 0.649351  ┆ … ┆ 0.818735  ┆ 0.979649  ┆ 530       ┆ 1016784  │
│ er qucibi ┆ 83688c4dc ┆ 21        ┆           ┆   ┆           ┆           ┆           ┆          │
│ alis      ┆ badb30c4c ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ d9d…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Lactob ┆ 1d359b1ed ┆ SRR111839 ┆ 0.37931   ┆ … ┆ 0.79991   ┆ 0.954887  ┆ 3258      ┆ 1016784  │
│ acillus   ┆ d19c41567 ┆ 21        ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ 8e7aa808a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 74f…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Holdem ┆ bf01a9a64 ┆ SRR111839 ┆ 0.744681  ┆ … ┆ 0.816401  ┆ 0.98606   ┆ 75        ┆ 1016784  │
│ anella    ┆ 4a5733f6e ┆ 21        ┆           ┆   ┆           ┆           ┆           ┆          │
│ porci     ┆ b479bc087 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 1b2…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Prevot ┆ 0a7f6f8dd ┆ SRR111839 ┆ 0.072165  ┆ … ┆ 0.750734  ┆ 0.882337  ┆ 69        ┆ 1016784  │
│ ella sp00 ┆ 523f18332 ┆ 21        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2251295   ┆ be6859dca ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ be8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Fimiso ┆ b46313db9 ┆ SRR111839 ┆ 0.8       ┆ … ┆ 0.786353  ┆ 0.98943   ┆ 7         ┆ 1016784  │
│ ma sp0023 ┆ 3705e9099 ┆ 21        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 20005     ┆ cef957650 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ d86…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__Sodali ┆ dfc599b97 ┆ SRR172414 ┆ 0.766187  ┆ … ┆ 0.829209  ┆ 0.987398  ┆ 16266     ┆ 16300045 │
│ philus    ┆ 0e8f63415 ┆ 98        ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp0045575 ┆ 4d8cb229e ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 65        ┆ 15c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Crypto ┆ 2e6b51456 ┆ SRR172414 ┆ 0.692671  ┆ … ┆ 0.814614  ┆ 0.982666  ┆ 7124      ┆ 16300045 │
│ bacteroid ┆ f82ce8125 ┆ 98        ┆           ┆   ┆           ┆           ┆           ┆          │
│ es sp9005 ┆ abc5339d5 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 469…      ┆ e08…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Prevot ┆ a678e51be ┆ SRR172414 ┆ 0.286932  ┆ … ┆ 0.778434  ┆ 0.94228   ┆ 322       ┆ 16300045 │
│ ella sp00 ┆ a46b3705b ┆ 98        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0434975   ┆ 5e9b425ca ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ a0b…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__UBA286 ┆ 379ae6e7c ┆ SRR172414 ┆ 0.475138  ┆ … ┆ 0.787543  ┆ 0.965185  ┆ 303       ┆ 16300045 │
│ 8 sp00455 ┆ dcf282ae9 ┆ 98        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2595      ┆ c6e99ef2f ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 8cb…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 277fdc52b ┆ SRR172414 ┆ 0.981818  ┆ … ┆ 0.797831  ┆ 0.999127  ┆ 784       ┆ 16300045 │
│ ricus sp0 ┆ d2436f63d ┆ 98        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ 641b78f41 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ fed…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
SUB_SPECIES2=(
             's__Cryptobacteroides sp900546925',
             's__Phascolarctobacterium_A succinatutens',
             's__Mogibacterium_A kristiansenii',
             's__Prevotella sp002251295',
#             's__Prevotella sp000434975',
#             's__Holdemanella porci',
)

for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    if row["query_name"] in SUB_SPECIES2:
        print(f"{row['percent']:.1f}% {row['query_name']} ")

94.1% s__Phascolarctobacterium_A succinatutens
97.6% s__Prevotella sp002251295
98.3% s__Cryptobacteroides sp900546925
99.4% s__Mogibacterium_A kristiansenii

In [11]:
for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    print(f"{row['percent']:.1f}% {row['query_name']} ")

34.5% s__JALFVM01 sp022787145
54.6% s__Fimisoma sp002320005
69.5% s__Roseburia inulinivorans
73.6% s__Holdemanella porci
87.3% s__Gemmiger qucibialis
90.0% s__UBA2868 sp004552595
94.1% s__Phascolarctobacterium_A succinatutens
94.7% s__Bariatricus sp004560705
97.6% s__Prevotella sp002251295
98.0% s__Prevotella sp000434975
98.3% s__Cryptobacteroides sp900546925
99.2% s__Lactobacillus amylovorus
99.4% s__Mogibacterium_A kristiansenii
99.5% s__Sodaliphilus sp004557565